Adicionado o gerenciamento de cobranças
RamonSilva20/mapos pull request #1102
Opened 2020-12-30 15:06 UTC by seitbnao

- Adiciona o gerenciamento de cobranças emitidas por link/boletos
- Permite deletar uma cobrança
- Permite Cancelar uma cobrança
- Permite Atualizar e confirmar pagamento de uma cobrança

![Screenshot_5](https://user-images.githubusercontent.com/11374956/103359859-6d590600-4a97-11eb-8586-5a9354c7f516.png)

2020-12-30 20:09 UTC, willph requested changes
Este arquivo não está com uma linha a mais do que a necessária? Apenas 1 linha em branco.

2020-12-30 20:25 UTC, willph requested changes
Arquivo da view **cobrancas.php**

`echo '<a style="margin-right: 1%" href="' . $r->payment_url . '" class="btn btn-info tip-top" title="Visualizar boleto"><i class="fas fa-barcode"></i></a>';`

Aqui nesse trecho de código realmente é `$r->payment_url`?
Pois o link do boleto esta sendo salvo em `link` e não em `payment_url`

O certo seria `$r->link` e com `target="_blank"` para abrir em outra pagina.

ficando assim o codigo: 

```
if ($this->permission->checkPermission($this->session->userdata('permissao'), 'eVenda') && $r->barcode != '') {
                            echo '<a style="margin-right: 1%" href="' . $r->link . '" class="btn btn-info tip-top" target="_blank" title="Visualizar boleto"><i class="fas fa-barcode"></i></a>';
                        }
```

2020-12-30 20:48 UTC, willph commented
O mesmo que foi feito para VENDAS precisa ser feito em OS também.

Parabéns pelo seu trabalho.

2020-12-30 20:57 UTC, willph commented
Percebe que não foi criado a permissão para esse novo submenu em `mapos/index.php/permissoes`, que fica nas seguintes pastas `application\views\permissoes\` 
`application\controllers\Permissoes.php`

@RamonSilva20 ou @Pr3d4dor poderá explicar melhor

2020-12-30 21:55 UTC, seitbnao commented
> Percebe que não foi criado a permissão para esse novo submenu em `mapos/index.php/permissoes`, que fica nas seguintes pastas `application\views\permissoes\`
> `application\controllers\Permissoes.php`
> 
> @RamonSilva20 ou @Pr3d4dor poderá explicar melhor

Já mandei um commit com suas resalvas. 👍

2020-12-30 22:52 UTC, willph requested changes
```if ($this->permission->checkPermission($this->session->userdata('permissao'), 'vVenda')) {```

Na view de cobrança faltou modificar  as permissões onde tem `vVenda`.... Por `vCobranca` e por aí vai.

Onde tiver permissão com venda, substituir  por cobrança.

2020-12-30 23:26 UTC, Pr3d4dor requested changes

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +
Sugestão: Remover linhas em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +        $this->load->library('Gateways/GerencianetSdk', null, 'GerencianetSdk');
Não seria bom deixar o Gateway de pagamento genêrico?

Eu acho que quando fosse gerado uma cobrança deve ser salvo em uma coluna em qual gateway de pagamento foi gerado aquela cobrança. Assim ficaria melhor para gerenciar e até receber os webhooks de retornos em quem tiver o sistema online

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +        ];
Sugestão: Remover linhas em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +            //Cobrança foi paga ou foi confirmada de forma manual, então damos baixa
Sugestão: Remover linhas em branco extra e comentário

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +                //TODO: dar baixa no lançamento caso exista
Vai ficar com TODO aqui mesmo?

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +        ];
Sugestão: Remover linhas em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +            //TODO: fazer a baixa do financeiro
Vai ficar com TODO aqui mesmo?

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +
Sugestão: Remover linhas em branco extra e comentário

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +        ];
Sugestão: Remover linhas em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Cobrancas.php
> +            log_info('Alterou um status de cobrança. ID' .  $change_id);
Faltou fazer algo aqui, igual os TODO anteriores.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Os.php
> +            $this->session->set_flashdata('error', 'Já existe cobrança vículadas neste OS, verifique em Financeiro/Cobranças');
```suggestion
            $this->session->set_flashdata('error', 'Já existe cobrança veículadas neste OS, verifique em Financeiro/Cobranças');
```

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Os.php
> +            }
Sugestão: Remover linhas em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Os.php
> +            $this->session->set_flashdata('error', 'Já existe cobrança vículadas neste OS, verifique em Financeiro/Cobranças');
```suggestion
            $this->session->set_flashdata('error', 'Já existe cobrança veículada neste OS, verifique em Financeiro/Cobranças');
```

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Os.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Permissoes.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Permissoes.php
> +
Sugestão: Remove linhas em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Vendas.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/controllers/Vendas.php
> +
Sugestão: Remover linha em branco extra

2020-12-30 23:26 UTC, Pr3d4dor commented on application/database/migrations/20201230231550_add_controle_cobrancas.php
> +        ## Create Table cobrancas
Sugestão: Remover comentário

2020-12-30 23:26 UTC, Pr3d4dor commented on application/database/migrations/20201230231550_add_controle_cobrancas.php
> +}
Se não for muito incômodo ou difícil, eu acho que talvez seria melhor deixar as colunas em portugues por causa que nas demais tabelas são em portugues, só para manter o padrão.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/libraries/Gateways/GerencianetSdk.php
> +define('ENABLE_SENDBOX', true);
Eu acho que seria melhor deixar essa constante no arquivo index.php igual às outras.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/libraries/Gateways/GerencianetSdk.php
> +    /* Cancela um boleto, link ou carne */
Sugestão: Remover comentário.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/libraries/Gateways/GerencianetSdk.php
> +    /* Faz o envio de uma cobranca seja link ou boletos para um email */
Sugestão: Remover comentário.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/libraries/Gateways/GerencianetSdk.php
> +    /* Retorna todas as informações de uma transação */
Sugestão: Remover comentário.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/libraries/Gateways/GerencianetSdk.php
> +    /* Marca uma transação como paga */
Sugestão: Remover comentário.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/models/Cobrancas_model.php
> +/* Location: ./application/models/cobrancas_model.php */
Sugestão: Remover comentário.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/models/Os_model.php
> +        return $this->db->get()->result();
Sugestão: Adicionar linha em branco antes do return.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/views/permissoes/adicionarPermissao.php
> +
Sugestão: Remover linha em branco.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/views/permissoes/editarPermissao.php
> +
Sugestão: Remover linha em branco.

2020-12-30 23:26 UTC, Pr3d4dor commented on application/views/permissoes/editarPermissao.php
> +
Sugestão: Remover linha em branco.

2020-12-30 23:26 UTC, Pr3d4dor commented on banco.sql
> +
Remover essas linhas.

2020-12-30 23:26 UTC, Pr3d4dor commented on banco.sql
> +  ADD PRIMARY KEY (`idCobranca`);
Sugestão: Ver nas outras tabelas como colocar a PRIMARY KEY diretamente.

2020-12-30 23:26 UTC, Pr3d4dor commented on updates/update_4.24.0_to_4.25.0.sql
> +  MODIFY `idCobranca` int(4) NOT NULL AUTO_INCREMENT;
Ver os comentários do banco.sql e fazer o mesmo

2020-12-30 23:27 UTC, Pr3d4dor commented
@seitbnao Obrigado pela contribuição, fiz alguns comentários.

2020-12-30 23:45 UTC, seitbnao commented
> @seitbnao Obrigado pela contribuição, fiz alguns comentários.

Opa, vlw já estou resolvendo suas resalvas

2020-12-30 23:46 UTC, seitbnao commented on application/controllers/Cobrancas.php
> +                //TODO: dar baixa no lançamento caso exista
Sim, por que tem q implementar essa parte

2020-12-31 00:20 UTC, willph requested changes
Tá ficando bom o negócio 😊

2020-12-31 00:20 UTC, willph commented on application/controllers/Os.php
> +            $this->session->set_flashdata('error', 'Já existe cobrança veículadas neste OS, verifique em Financeiro/Cobranças');
```$this->session->set_flashdata('error', 'Já existe cobrança veículadas neste OS, verifique em Financeiro/Cobranças');```

O certo seria **veiculada nesta OS**?

2020-12-31 00:20 UTC, willph commented on application/controllers/Os.php
> +            $this->session->set_flashdata('error', 'Já existe cobrança veículadas neste OS, verifique em Financeiro/Cobranças');
```$this->session->set_flashdata('error', 'Já existe cobrança veículadas neste OS, verifique em Financeiro/Cobranças');```

O certo seria **veiculada nesta OS**?

2020-12-31 00:26 UTC, seitbnao commented
> Tá ficando bom o negócio 😊

espero que sim kk 👯

2020-12-31 00:27 UTC, Pr3d4dor commented on index.php
> +define('ENABLE_SENDBOX', true);
Sugestão: Eu acho que o nome da variável poderia ser: 

```suggestion
define('PAGAMENTOS_MODO_SANDBOX', true);
```

2020-12-31 00:31 UTC, willph commented
Eu também já me atrapalhei muito com essa tal de linha GIT. 😁

É uma linha em branco que tem que deixar em alguns arquivos  no final do código fonte.

Apenas 1.

Terminou o código, da um enter e deixa lá a linha em branco.

O @Pr3d4dor pode explicar melhor essa linha GIT

2020-12-31 00:33 UTC, seitbnao commented
> Eu também já me atrapalhei muito com essa tal de linha GIT. 😁
> 
> É uma linha em branco que tem que deixar em alguns arquivos no final do código fonte.
> 
> Apenas 1.
> 
> Terminou o código, da um enter e deixa lá a linha em branco.
> 
> O @Pr3d4dor pode explicar melhor essa linha GIT

mais isso é bom, aprende os padrões, mais é mania mesmo "enter" "enter" kk

2020-12-31 01:02 UTC, willph commented
> > Eu também já me atrapalhei muito com essa tal de linha GIT. 😁
> > É uma linha em branco que tem que deixar em alguns arquivos no final do código fonte.
> > Apenas 1.
> > Terminou o código, da um enter e deixa lá a linha em branco.
> > O @Pr3d4dor pode explicar melhor essa linha GIT
> 
> mais isso é bom, aprende os padrões, mais é mania mesmo "enter" "enter" kk

Finalizou tudo?

2020-12-31 01:06 UTC, seitbnao commented
> > > Eu também já me atrapalhei muito com essa tal de linha GIT. 😁
> > > É uma linha em branco que tem que deixar em alguns arquivos no final do código fonte.
> > > Apenas 1.
> > > Terminou o código, da um enter e deixa lá a linha em branco.
> > > O @Pr3d4dor pode explicar melhor essa linha GIT
> > 
> > 
> > mais isso é bom, aprende os padrões, mais é mania mesmo "enter" "enter" kk
> 
> Finalizou tudo?

Acredito que sim o/

2020-12-31 01:42 UTC, Pr3d4dor approved these changes

2020-12-31 01:42 UTC, Pr3d4dor commented
@seitbnao Vou deixar aprovado por enquanto, amanhã vou dar mais uma olhada e fazer o merge se não tiver mais nada.

2020-12-31 11:53 UTC, willph requested changes
Acho que só faltou isso num foi?

2020-12-31 11:53 UTC, willph commented on updates/update_4.24.0_to_4.25.0.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Está faltando a linha GIT aqui no final do código fonte?

2020-12-31 12:47 UTC, seitbnao commented on updates/update_4.24.0_to_4.25.0.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8;
mds kkk pronto

2020-12-31 12:49 UTC, willph approved these changes

2020-12-31 12:53 UTC, willph commented
Parabéns pelo seu trabalho.

Se cada um de nós dermos um tempinho do nosso tempo livre para esse projeto ele ficará TOP. 

Aguardo o merge de @Pr3d4dor do código. 

Feliz ano Novo!
Obrigado.

2020-12-31 13:05 UTC, seitbnao commented
> Parabéns pelo seu trabalho.
> 
> Se cada um de nós dermos um tempinho do nosso tempo livre para esse projeto ele ficará TOP.
> 
> Aguardo o merge de @Pr3d4dor do código.
> 
> Feliz ano Novo!
> Obrigado.

Obg, Feliz ano Novo!, para todos.

2020-12-31 13:33 UTC, willph reviewed
Foi bom ter acrescentado o valor. 

Depois vê se é viável criar um visualizarCobranca onde trará todos os detalhes e o histórico. 

Vi que o Json tem um campo chamado histórico. 

O que achas?

2020-12-31 14:53 UTC, seitbnao commented
> Foi bom ter acrescentado o valor.
> 
> Depois vê se é viável criar um visualizarCobranca onde trará todos os detalhes e o histórico.
> 
> Vi que o Json tem um campo chamado histórico.
> 
> O que achas?

Verdade, visualizar o histórico do pagamento seria bacana

2020-12-31 20:58 UTC, willph commented
> > Foi bom ter acrescentado o valor.
> > Depois vê se é viável criar um visualizarCobranca onde trará todos os detalhes e o histórico.
> > Vi que o Json tem um campo chamado histórico.
> > O que achas?
> 
> Verdade, visualizar o histórico do pagamento seria bacana
> 
> Estava testando, o dataTable achei bacana
> ![Screenshot_10](https://user-images.githubusercontent.com/11374956/103415123-904eed00-4b5f-11eb-997c-41442ebb1214.png)

Carregar uma quantidade X por página?
O código Está no sei github?

Por aí baixo pra testar

2021-01-01 03:14 UTC, seitbnao commented
> > > Foi bom ter acrescentado o valor.
> > > Depois vê se é viável criar um visualizarCobranca onde trará todos os detalhes e o histórico.
> > > Vi que o Json tem um campo chamado histórico.
> > > O que achas?
> > 
> > Verdade, visualizar o histórico do pagamento seria bacana
> > 
> > Estava testando, o dataTable achei bacana
> > ![Screenshot_10](https://user-images.githubusercontent.com/11374956/103415123-904eed00-4b5f-11eb-997c-41442ebb1214.png)
> 
> Carregar uma quantidade X por página?
> O código Está no sei github?
> 
> Por aí baixo pra testar

Datatable deixa as tabelas dinâmica facilita pesquisa

2021-01-01 03:38 UTC, willph commented
Feliz ano Novo pra ti.
Espero que continue conosco nesse 2021.

Tudo de bom. 🤝👍

2021-01-02 03:36 UTC, merged

2021-01-02 12:51 UTC, willph commented
Criar nova PR com a seguintes correções:

Faltou adicionar chave estrangeiras em venda_id e os_is na tabela cobranças.

2021-01-02 13:03 UTC, willph commented
Estou fazendo essa alterações. Em breve envio