feature: notificação whatsapp personalizada
RamonSilva20/mapos pull request #1127
Opened 2021-01-10 14:46 UTC by seitbnao

![Screenshot_12](https://user-images.githubusercontent.com/11374956/104126080-7076b080-5339-11eb-9917-457f181e19c5.png)

2021-01-10 19:20 UTC, seitbnao commented
PR Finalizada.

2021-01-10 20:40 UTC, seitbnao commented
PR Finalizada.
Caso ocorra o merge, alterar versão para 4.27.0

2021-01-10 21:25 UTC, Pr3d4dor commented on application/views/os/visualizarOs.php
> +    echo '<a title="Enviar Por WhatsApp" class="btn btn-mini btn-success" id="enviarWhatsApp" target="_blank" href="https://web.whatsapp.com/send?phone=55' . $zapnumber . '&text=' . $str . '"><i clas
Não acho ideial fazer esse tipo de processamento na view.

2021-01-10 21:26 UTC, Pr3d4dor commented on application/views/tema/conteudo.php
> +          <?php if ($var = $this->session->flashdata('success')): ?><script>swal("Sucesso!", "<?php echo $var; ?>", "success");</script><?php endif; ?>
Ficou um pouco estranho colocar várias vezes a tag script.

2021-01-10 21:26 UTC, Pr3d4dor commented on application/views/os/os.php
> +                                echo '<a class="btn btn-success tip-top" style="margin-right: 1%" title="Enviar Por WhatsApp" id="enviarWhatsApp" target="_blank" href="https://web.whatsapp.com/send?p
Mesma questão referente ao outro comentário.

2021-01-10 21:27 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +                                                echo '<a title="Enviar Por WhatsApp" class="btn btn-success" id="enviarWhatsApp" target="_blank" href="https://web.whatsapp.com/send?phone=55' . $zapnu
Mesma questão referente ao outro comentário e repetindo o mesmo trecho de código 3 vezes. Melhor fazer uma função que faça isso e não realizar isso na view, fazer no controller.

2021-01-10 21:27 UTC, Pr3d4dor commented on application/views/mapos/configurar.php
> +        });
Arrumar identação.

2021-01-10 21:28 UTC, Pr3d4dor commented on application/database/migrations/20210110153941_feature_notificawhats.php
> +        $this->dbforge->drop_table('configuracoes');
O down está incorreto, está dropando a tabela inteira, o correto é fazer o contrário da SQL de cima.

2021-01-10 21:28 UTC, Pr3d4dor commented on application/controllers/Os.php
> +        $this->data['str'] = $str = $this->data['configuration']['notifica_whats'];
Melhorar o nome da variável, str é muito confuso.

2021-01-11 00:26 UTC, seitbnao commented on application/views/tema/conteudo.php
> +          <?php if ($var = $this->session->flashdata('success')): ?><script>swal("Sucesso!", "<?php echo $var; ?>", "success");</script><?php endif; ?>
não consegui ver uma forma para simplificar

2021-01-11 00:45 UTC, willph commented
Amanhã eu baixo e testo tudo.

Ótima noite.

2021-01-11 14:13 UTC, willph commented
Ola, tudo bom?

Você testou fazer uma instalação do zero para vê se tudo funcionava direito?

2021-01-11 14:26 UTC, willph requested changes

2021-01-11 14:26 UTC, willph commented on updates/update_3.14.2_to_3.15.0.sql
> +(7, 'notifica_whats', '');
Acredito que este arquivo não era pra ser alterado  `updates/update_3.14.2_to_3.15.0.sql`

2021-01-11 14:26 UTC, willph commented on banco.sql
>  (6, 'control_estoque', '1');
Você esqueceu de remover os `;`  o certo `(6, 'control_estoque', '1'),` para poder adicionar nova linha.

Aconselho mais uma vez, antes de envia uma PR teste bem e revise o código-fonte.

2021-01-11 14:51 UTC, seitbnao commented on banco.sql
>  (6, 'control_estoque', '1');
Chegando do serviço vou reinstalar

2021-01-11 18:05 UTC, seitbnao commented on updates/update_3.14.2_to_3.15.0.sql
> +(7, 'notifica_whats', '');
n mesmo =z

2021-01-11 19:01 UTC, willph commented
Por algum motivo não está criando mais o usuário na hora da instalação. Por Favor testar com banco de dados zerado e usar a instalação do mapos.

2021-01-11 19:34 UTC, seitbnao commented
> Por algum motivo não está criando mais o usuário na hora da instalação. Por Favor testar com banco de dados zerado e usar a instalação do mapos.

@willph baixei instalei criou normalmente, também criei o usuário 2

2021-01-11 19:49 UTC, willph commented
> 
> 
> > Por algum motivo não está criando mais o usuário na hora da instalação. Por Favor testar com banco de dados zerado e usar a instalação do mapos.
> 
> @willph baixei instalei criou normalmente, também criei o usuário 2
> vou testar novamente

Acabei de testar de novo. E não criou no processo de instalação.

![image](https://user-images.githubusercontent.com/17226802/104230894-edcf1d80-542c-11eb-9c4c-b6f72156758c.png)

2021-01-11 20:00 UTC, seitbnao commented
> > > Por algum motivo não está criando mais o usuário na hora da instalação. Por Favor testar com banco de dados zerado e usar a instalação do mapos.
> > 
> > 
> > @willph baixei instalei criou normalmente, também criei o usuário 2
> > vou testar novamente
> 
> Acabei de testar de novo. E não criou no processo de instalação.
> 
> ![image](https://user-images.githubusercontent.com/17226802/104230894-edcf1d80-542c-11eb-9c4c-b6f72156758c.png)

Pois é olhei aqui novamente, era o texto do whatss a estrutura do banco não tinha sido alterada pra suportar um texto

2021-01-11 20:16 UTC, seitbnao commented
Will tem algum editor ou coder para ta editando o mapos, eu uso o visual code, e parece que as vezes ele buga os arquivos

2021-01-11 20:26 UTC, willph commented
> 
> 
> Will tem algum editor ou coder para ta editando o mapos, eu uso o visual code, e parece que as vezes ele buga os arquivos

Eu uso ele também Visual Code Studio

2021-01-11 21:02 UTC, seitbnao commented
Único erro era esse da instalação Wil

2021-01-11 21:47 UTC, willph commented
> Único erro era esse da instalação Wil

Vou analisar detalhadamente. 

Hoje foi corrido 😁

2021-01-12 00:01 UTC, willph commented
> 
> 
> Único erro era esse da instalação Wil

Tem erro no detalhamento de uma cobrança no campo `Emitida em` a data vem errada.
Gere um boleto e depois vai em cobrança e clique em visualizarCobranca e você verá o erro na data.

2021-01-12 00:25 UTC, willph commented
Não sei se ai esta assim, mas aqui ainda encontra o bug que não aparece o gráfico de anos anteriores

![image](https://user-images.githubusercontent.com/17226802/104253532-73fe5a80-5453-11eb-8f99-9bd79bb212b4.png)

2021-01-12 00:30 UTC, willph commented
Nem todas as views está no padrão switchalert2, mas isso vamos vendo com o tempo é tranquilo. 

Amanhã faço mais testes.

2021-01-12 11:14 UTC, seitbnao commented
> Nem todas as views está no padrão switchalert2, mas isso vamos vendo com o tempo é tranquilo.
> 
> Amanhã faço mais testes.

Pode dizer quais que você viu que não está?

> Não sei se ai esta assim, mas aqui ainda encontra o bug que não aparece o gráfico de anos anteriores
> 
> ![image](https://user-images.githubusercontent.com/17226802/104253532-73fe5a80-5453-11eb-8f99-9bd79bb212b4.png)

Estou tentando entender o porque de não aparecer executando a consulta no banco aparece todas as informações

2021-01-12 11:21 UTC, seitbnao commented
> > Nem todas as views está no padrão switchalert2, mas isso vamos vendo com o tempo é tranquilo.
> > Amanhã faço mais testes.
> 
> Pode dizer quais que você viu que não está?
> 
> > Não sei se ai esta assim, mas aqui ainda encontra o bug que não aparece o gráfico de anos anteriores
> > ![image](https://user-images.githubusercontent.com/17226802/104253532-73fe5a80-5453-11eb-8f99-9bd79bb212b4.png)
> 
> Estou tentando entender o porque de não aparecer executando a consulta no banco aparece todas as informações
Pelo que notei é 
um erro de js ,que aparece só quando você usa o pesquisar o ano
![Screenshot_9](https://user-images.githubusercontent.com/11374956/104308276-27486d00-54af-11eb-98a9-14785df09e28.png)

2021-01-12 12:41 UTC, willph commented
> 
> 
> > Único erro era esse da instalação Wil
> 
> Tem erro no detalhamento de uma cobrança no campo `Emitida em` a data vem errada.
> Gere um boleto e depois vai em cobrança e clique em visualizarCobranca e você verá o erro na data.
> 
> Verifica se o dado esta vindo corretamente, `<?php echo date(('d/m/Y'), strtotime($result->dataVenda)); ?>`

Vi que no BD já tem o campo `created_at` que tal salvar no bd e puxar do bd?

2021-01-12 13:15 UTC, seitbnao commented
> > 
> > 
> > > Único erro era esse da instalação Wil
> > 
> > Tem erro no detalhamento de uma cobrança no campo `Emitida em` a data vem errada.
> > Gere um boleto e depois vai em cobrança e clique em visualizarCobranca e você verá o erro na data.
> > 
> > Verifica se o dado esta vindo corretamente, `<?php echo date(('d/m/Y'), strtotime($result->dataVenda)); ?>`
> 
> Vi que no BD já tem o campo `created_at` que tal salvar no bd e puxar do bd?

Já fiz a alteração tô olhando o erro dos gráficos

2021-01-12 13:19 UTC, willph commented
> 
> 
> > > > Único erro era esse da instalação Wil
> > > 
> > > 
> > > Tem erro no detalhamento de uma cobrança no campo `Emitida em` a data vem errada.
> > > Gere um boleto e depois vai em cobrança e clique em visualizarCobranca e você verá o erro na data.
> > > Verifica se o dado esta vindo corretamente, `<?php echo date(('d/m/Y'), strtotime($result->dataVenda)); ?>`
> > 
> > 
> > Vi que no BD já tem o campo `created_at` que tal salvar no bd e puxar do bd?
> 
> Já fiz a alteração tô olhando o erro dos gráficos

A data de criação do boleto e link ja esta sendo salva no bd?

2021-01-12 13:25 UTC, seitbnao commented
> > > > > Único erro era esse da instalação Wil
> > > > 
> > > > 
> > > > Tem erro no detalhamento de uma cobrança no campo `Emitida em` a data vem errada.
> > > > Gere um boleto e depois vai em cobrança e clique em visualizarCobranca e você verá o erro na data.
> > > > Verifica se o dado esta vindo corretamente, `<?php echo date(('d/m/Y'), strtotime($result->dataVenda)); ?>`
> > > 
> > > 
> > > Vi que no BD já tem o campo `created_at` que tal salvar no bd e puxar do bd?
> > 
> > 
> > Já fiz a alteração tô olhando o erro dos gráficos
> 
> A data de criação do boleto e link ja esta sendo salva no bd?

sim, os retornos são salvos

2021-01-12 13:32 UTC, willph commented
Não sei se ai esta assim, mas aqui ainda encontra o bug que não aparece o gráfico de anos anteriores

![Uploading image.png…]()


> 
> 
> > > > > > Único erro era esse da instalação Wil
> > > > > 
> > > > > 
> > > > > Tem erro no detalhamento de uma cobrança no campo `Emitida em` a data vem errada.
> > > > > Gere um boleto e depois vai em cobrança e clique em visualizarCobranca e você verá o erro na data.
> > > > > Verifica se o dado esta vindo corretamente, `<?php echo date(('d/m/Y'), strtotime($result->dataVenda)); ?>`
> > > > 
> > > > 
> > > > Vi que no BD já tem o campo `created_at` que tal salvar no bd e puxar do bd?
> > > 
> > > 
> > > Já fiz a alteração tô olhando o erro dos gráficos
> > 
> > 
> > A data de criação do boleto e link ja esta sendo salva no bd?
> 
> sim, os retornos são salvos
> [06f7958](https://github.com/RamonSilva20/mapos/commit/06f7958da63c7ebd9770991103be73a6fb59549f)

Eu analisei e não esta quando cria o BD

O CODIGO QUE ESTA

```
 $os = $this->os_model->getById($this->input->post('idOs'));
        $obj = json_decode($pagamento);
        if ($obj->code == 200) {
            $data = [
                'barcode' => $obj->data->barcode,
                'link' => $obj->data->link,
                'pdf' => $obj->data->pdf->charge,
                'expire_at' => $obj->data->expire_at,
                'charge_id' => $obj->data->charge_id,
                'status' => $obj->data->status,
                'total' =>  $this->input->post('totalValor'),
                'payment' => $obj->data->payment,
                'os_id' => $this->input->post('idOs'),
                'clientes_id' => $os->idClientes,

FALTA ESSE CAMPO                ` 'created_at' => $obj->data->created_at,`

Crie um boleto de cobrança e analise o BD pra vê se esta salvando
```

2021-01-12 13:37 UTC, seitbnao commented
> Não sei se ai esta assim, mas aqui ainda encontra o bug que não aparece o gráfico de anos anteriores
> 
> 
> 
> Único erro era esse da instalação Wil
> 
> Tem erro no detalhamento de uma cobrança no campo Emitida em a data vem errada.
> Gere um boleto e depois vai em cobrança e clique em visualizarCobranca e você verá o erro na data.
> Verifica se o dado esta vindo corretamente, <?php echo date(('d/m/Y'), strtotime($result->dataVenda)); ?>
> 
> Vi que no BD já tem o campo created_at que tal salvar no bd e puxar do bd?
> 
> Já fiz a alteração tô olhando o erro dos gráficos
> 
> A data de criação do boleto e link ja esta sendo salva no bd?
> 
> sim, os retornos são salvos
> 06f7958
> 
> Eu analisei e não esta quando cria o BD
> 
> O CODIGO QUE ESTA
> 
>  $os = $this->os_model->getById($this->input->post('idOs'));
>         $obj = json_decode($pagamento);
>         if ($obj->code == 200) {
>             $data = [
>                 'barcode' => $obj->data->barcode,
>                 'link' => $obj->data->link,
>                 'pdf' => $obj->data->pdf->charge,
>                 'expire_at' => $obj->data->expire_at,
>                 'charge_id' => $obj->data->charge_id,
>                 'status' => $obj->data->status,
>                 'total' =>  $this->input->post('totalValor'),
>                 'payment' => $obj->data->payment,
>                 'os_id' => $this->input->post('idOs'),
>                 'clientes_id' => $os->idClientes,
> 
> FALTA ESSE CAMPO                ` 'created_at' => $obj->data->created_at,`
> 
> Crie um boleto de cobrança e analise o BD pra vê se esta salvando

Wil boletos não retorna create_at

2021-01-12 13:42 UTC, willph commented
Então so link de pagamento retorna? kkkkk eita Viajei agora.
Então era por isso que o código quebrava

2021-01-12 13:43 UTC, seitbnao commented
> Então so link de pagamento retorna? kkkkk eita Viajei agora.
> Então era por isso que o código quebrava

condicionei
`                                if($gerencianet->data->created_at != null) {
                                    echo date(('d/m/Y H:i:s'), strtotime($gerencianet->data->created_at));
                                }
                                else {
                                    echo date(('d/m/Y'), strtotime($result->dataVenda));
                                }`

2021-01-12 13:45 UTC, seitbnao commented
> > Então so link de pagamento retorna? kkkkk eita Viajei agora.
> > Então era por isso que o código quebrava
> 
> condicionei caso seja boleto, pegue a data da criação da venda, e link a data da criação do link

sobre o erro do gráfico, apenas o ano 2020 apresenta aquele erro, ainda não sei o porque estou olhando, testei com 2017 2018 2019 2021 e no 2020 puff..

2021-01-12 14:05 UTC, seitbnao commented on application/views/cobrancas/visualizarCobranca.php
> +                                <?php
Eu removi wil, Não tem porque exibir a criação, isso já é feito no históricco

2021-01-12 14:09 UTC, willph commented
Verdade. 
Então esse campo em detalhes nem precisava, se já vem em baixo

2021-01-12 14:10 UTC, seitbnao commented
> Verdade.
> Então esse campo em detalhes nem precisava, se já vem em baixo
Deixei como a data da os ou da venda

2021-01-12 14:15 UTC, seitbnao commented
As cobranças acho oque realmente falta mesmo, e criar o retorno da api, e realizar as baixas no financeiro, creio que também teríamos de mudar como  o lançamento é inserido, digo gerar venda já gera o lançamento dessa venda, gerou uma OS já gera o lançamento dessa OS, pra depois faturar o lançamento e não a OS ou venda, não sei se meu raciocínio ta certo

2021-01-12 14:18 UTC, willph commented
> As cobranças acho oque realmente falta mesmo, e criar o retorno da api, e realizar as baixas no financeiro, creio que também teríamos de mudar como o lançamento é inserido, digo gerar venda já gera o lançamento dessa venda, gerou uma OS já gera o lançamento dessa OS, pra depois faturar o lançamento e não a OS ou venda, não sei se meu raciocínio ta certo

@RamonSilva20 diga aí o seu posicionamento?

2021-01-12 23:05 UTC, Pr3d4dor commented
O que falta para poder mergear essa PR?

2021-01-12 23:10 UTC, seitbnao commented
> O que falta para poder mergear essa PR?

acho que já pode

2021-01-13 00:21 UTC, willph commented
> 
> 
> > Verdade.
> > Então esse campo em detalhes nem precisava, se já vem em baixo
> > Deixei como a data da os ou da venda



> 
> 
> O que falta para poder mergear essa PR?

Falta ajeita a nomenclatura de **Emitida em** em detalhamento de cobrança.

2021-01-13 05:44 UTC, willph approved these changes

2021-01-13 10:45 UTC, willph commented
Pronto. Só aguardar o merge de @Pr3d4dor .

E qualquer coisa o que for aparecendo nos vamos corrigindo. 😁

2021-01-14 01:19 UTC, merged