feature: issue #1140
RamonSilva20/mapos pull request #1146
Opened 2021-01-14 16:13 UTC by seitbnao

Habilita ou desabilita a edição de data de pagamento retroativa ou futura.

![Screenshot_11](https://user-images.githubusercontent.com/11374956/104617502-45a69800-566a-11eb-9b48-d4111dd8699b.png)

![Screenshot_12](https://user-images.githubusercontent.com/11374956/104617507-463f2e80-566a-11eb-9991-b8dc0f1868c7.png)

2021-01-14 16:15 UTC, willph commented
> Habilita ou desabilita a edição de data de pagamento retroativa ou futura.
> 
> ![Screenshot_11](https://user-images.githubusercontent.com/11374956/104617502-45a69800-566a-11eb-9b48-d4111dd8699b.png)
> 
> ![Screenshot_12](https://user-images.githubusercontent.com/11374956/104617507-463f2e80-566a-11eb-9991-b8dc0f1868c7.png)

Em configurações, sistema?
Para desabilitar e habilita?

2021-01-14 16:27 UTC, seitbnao commented
> > Habilita ou desabilita a edição de data de pagamento retroativa ou futura.
> > ![Screenshot_11](https://user-images.githubusercontent.com/11374956/104617502-45a69800-566a-11eb-9b48-d4111dd8699b.png)
> > ![Screenshot_12](https://user-images.githubusercontent.com/11374956/104617507-463f2e80-566a-11eb-9991-b8dc0f1868c7.png)
> 
> Em configurações, sistema?
> Para desabilitar e habilita?

sim

2021-01-14 16:30 UTC, willph commented
> > > Habilita ou desabilita a edição de data de pagamento retroativa ou futura.
> > > ![Screenshot_11](https://user-images.githubusercontent.com/11374956/104617502-45a69800-566a-11eb-9b48-d4111dd8699b.png)
> > > ![Screenshot_12](https://user-images.githubusercontent.com/11374956/104617507-463f2e80-566a-11eb-9991-b8dc0f1868c7.png)
> > 
> > 
> > Em configurações, sistema?
> > Para desabilitar e habilita?
> 
> sim

Aproveita e faz um teste aí no teu.

O meu não está aparecendo a mensagem de OS adicionada com sucesso.

2021-01-14 16:32 UTC, seitbnao commented
> > > > Habilita ou desabilita a edição de data de pagamento retroativa ou futura.
> > > > ![Screenshot_11](https://user-images.githubusercontent.com/11374956/104617502-45a69800-566a-11eb-9b48-d4111dd8699b.png)
> > > > ![Screenshot_12](https://user-images.githubusercontent.com/11374956/104617507-463f2e80-566a-11eb-9991-b8dc0f1868c7.png)
> > > 
> > > 
> > > Em configurações, sistema?
> > > Para desabilitar e habilita?
> > 
> > 
> > sim
> 
> Aproveita e faz um teste aí no teu.
> 
> O meu não está aparecendo a mensagem de OS adicionada com sucesso.

ta beleza. vou testar

2021-01-14 16:33 UTC, seitbnao commented
![Screenshot_13](https://user-images.githubusercontent.com/11374956/104619896-20ffef80-566d-11eb-8bb7-1836d6412e52.png)

2021-01-14 17:01 UTC, willph commented
Percebi outro erro mas acredito que era antigo, mensagem de uma View aparecendo em outra 😅

No teu acontece isso também?

2021-01-14 17:27 UTC, seitbnao commented
> Percebi outro erro mas acredito que é antigo, mensagem de uma View aparecendo em outra 😅
> 
> No teu acontece isso também?

deve ser antigo, não mechi muito nessa PR, ql msg ta aparecendo ? em ql View

2021-01-14 17:29 UTC, willph commented
> > Percebi outro erro mas acredito que é antigo, mensagem de uma View aparecendo em outra 😅
> > No teu acontece isso também?
> 
> deve ser antigo, não mechi muito nessa PR, ql msg ta aparecendo ? em ql View

Já já mando a foto pra você vê.

2021-01-14 18:51 UTC, willph commented
Olha, ao cria o pagamento de um boleto, se depois disso sair pra qualquer view aparece a mensagem da foto.Pensei que essa mensagem so iria aparece quando fosse para o menu cobrança.

![image](https://user-images.githubusercontent.com/17226802/104635074-30d4ff00-5680-11eb-82bb-cbb8b1527cb3.png)

2021-01-14 18:53 UTC, willph commented
O do lado foi de brinde, porque minha filha assiste desenho enquanto eu dou uma olhada kkkkkk

2021-01-14 19:30 UTC, seitbnao commented
> O do lado foi de brinde, porque minha filha assiste desenho enquanto eu dou uma olhada kkkkkk

vi aqui Wil, essa msg tem que ser removida, por causa do carregamento da criação da cobrança em ajax que sobe o modal de confirmação, como faz isso nao recarrega a janela, para mostrar o alert,

2021-01-14 20:46 UTC, willph commented
Quando você estava alterando a lógica em relatório acho que quebrou o funcionamento de gerar etiqueta?

![image](https://user-images.githubusercontent.com/17226802/104647211-46522500-5690-11eb-8ba2-a4d0f3f80627.png)

2021-01-14 20:49 UTC, seitbnao commented
> Quando você estava alterando a lógica em relatório acho que quebrou o funcionamento de gerar etiqueta?
> 
> ![image](https://user-images.githubusercontent.com/17226802/104647211-46522500-5690-11eb-8ba2-a4d0f3f80627.png)

Acredito que não wil, a alteração so foi adicionar o valor total na consulta que não estava vindo

2021-01-14 20:49 UTC, willph commented
Ou não chegou a mexer nessa area? 

Vou vê se identifico aqui o erro

2021-01-14 20:50 UTC, willph commented
> 
> 
> > Quando você estava alterando a lógica em relatório acho que quebrou o funcionamento de gerar etiqueta?
> > ![image](https://user-images.githubusercontent.com/17226802/104647211-46522500-5690-11eb-8ba2-a4d0f3f80627.png)
> 
> Acredito que não wil, a alteração so foi adicionar o valor total na consulta que não estava vindo

Beleza, vou verificar o que houve então.

2021-01-14 20:50 UTC, seitbnao commented
> > > Quando você estava alterando a lógica em relatório acho que quebrou o funcionamento de gerar etiqueta?
> > > ![image](https://user-images.githubusercontent.com/17226802/104647211-46522500-5690-11eb-8ba2-a4d0f3f80627.png)
> > 
> > 
> > Acredito que não wil, a alteração so foi adicionar o valor total na consulta que não estava vindo
> 
> Beleza, vou verificar o que houve então.

Olha o valor do código de barras tem tipo de códigos que não aceita qualquer valor

2021-01-14 20:56 UTC, willph commented
> 
> 
> > > > Quando você estava alterando a lógica em relatório acho que quebrou o funcionamento de gerar etiqueta?
> > > > ![image](https://user-images.githubusercontent.com/17226802/104647211-46522500-5690-11eb-8ba2-a4d0f3f80627.png)
> > > 
> > > 
> > > Acredito que não wil, a alteração so foi adicionar o valor total na consulta que não estava vindo
> > 
> > 
> > Beleza, vou verificar o que houve então.
> 
> Olha o valor do código de barras tem tipo de códigos que não aceita qualquer valor

Parece que não esta passando o numero

> 
> 
> > > > Quando você estava alterando a lógica em relatório acho que quebrou o funcionamento de gerar etiqueta?
> > > > ![image](https://user-images.githubusercontent.com/17226802/104647211-46522500-5690-11eb-8ba2-a4d0f3f80627.png)
> > > 
> > > 
> > > Acredito que não wil, a alteração so foi adicionar o valor total na consulta que não estava vindo
> > 
> > 
> > Beleza, vou verificar o que houve então.
> 
> Olha o valor do código de barras tem tipo de códigos que não aceita qualquer valor

Acredito que é outra coisa, testa ai no teu por favor, qr-code, codebar..... Vi retorno diferente

2021-01-14 20:57 UTC, seitbnao commented
> > > > > Quando você estava alterando a lógica em relatório acho que quebrou o funcionamento de gerar etiqueta?
> > > > > ![image](https://user-images.githubusercontent.com/17226802/104647211-46522500-5690-11eb-8ba2-a4d0f3f80627.png)
> > > > 
> > > > 
> > > > Acredito que não wil, a alteração so foi adicionar o valor total na consulta que não estava vindo
> > > 
> > > 
> > > Beleza, vou verificar o que houve então.
> > 
> > 
> > Olha o valor do código de barras tem tipo de códigos que não aceita qualquer valor
> 
> Parece que não esta passando o numero
> 
> > > > > Quando você estava alterando a lógica em relatório acho que quebrou o funcionamento de gerar etiqueta?
> > > > > ![image](https://user-images.githubusercontent.com/17226802/104647211-46522500-5690-11eb-8ba2-a4d0f3f80627.png)
> > > > 
> > > > 
> > > > Acredito que não wil, a alteração so foi adicionar o valor total na consulta que não estava vindo
> > > 
> > > 
> > > Beleza, vou verificar o que houve então.
> > 
> > 
> > Olha o valor do código de barras tem tipo de códigos que não aceita qualquer valor
> 
> Acredito que é outra coisa, testa ai no teu por favor, qr-code, codebar..... Vi retorno diferente

è oque eu lhe disse Will, certos padrões aceita certos valos e certo tamanho de string

2021-01-14 21:08 UTC, willph commented
> 
> 
> É oque eu lhe disse Will, certos padrões aceita certos valores e certo tamanho de string, no mapos isso está generalizado ai pode ocorrer esses erros, oque podemos fazer é emitir um alert de que o código usado não é válido para o padrão escolhido
> 
> https://loja.automatech.com.br/blogs/blog/sobre-padroes-de-codigos-de-barras?keyword=&gclid=Cj0KCQiA9P__BRC0ARIsAEZ6irh2anQ0BMcmr84uO4Nltw-mkwdCFRXLeKYoCKdr4owdTls0yTTrNcQaAmaDEALw_wcB

Estranho kkkkk no meu ate QR-Code esta falhando kkkkk 
![image](https://user-images.githubusercontent.com/17226802/104649272-41db3b80-5693-11eb-9a40-fbf6ea9e3950.png)

Meu pc ta querendo comer meu juizo e de quebra o dos outros kkkkkk


Então ta tudo ok, não tem mais bug ate que se encontre

2021-01-14 21:12 UTC, seitbnao commented
> > É oque eu lhe disse Will, certos padrões aceita certos valores e certo tamanho de string, no mapos isso está generalizado ai pode ocorrer esses erros, oque podemos fazer é emitir um alert de que o código usado não é válido para o padrão escolhido
> > https://loja.automatech.com.br/blogs/blog/sobre-padroes-de-codigos-de-barras?keyword=&gclid=Cj0KCQiA9P__BRC0ARIsAEZ6irh2anQ0BMcmr84uO4Nltw-mkwdCFRXLeKYoCKdr4owdTls0yTTrNcQaAmaDEALw_wcB
> 
> Estranho kkkkk no meu ate QR-Code esta falhando kkkkk
> ![image](https://user-images.githubusercontent.com/17226802/104649272-41db3b80-5693-11eb-9a40-fbf6ea9e3950.png)
> 
> Meu pc ta querendo comer meu juizo e de quebra o dos outros kkkkkk
> 
> Então ta tudo ok, não tem mais bug ate que se encontre

esse ai que mostrou acabei de mandar o commit, ele ocorre por que as msg de alert não podem conter ASPAS

2021-01-14 21:49 UTC, willph commented
Faltou enviar o `composer.lock`?

2021-01-14 21:49 UTC, seitbnao commented
> Faltou enviar o `composer.lock`?

fiquei na dúvida se podia ou não kkk vou enviar

2021-01-14 21:51 UTC, willph commented
> 
> 
> > Faltou enviar o `composer.lock`?
> 
> fiquei na dúvida se podia ou não kkk vou enviar

antes executa o composer update visse 👍

2021-01-14 21:52 UTC, seitbnao commented
protinho

2021-01-14 22:01 UTC, willph commented
> 
> 
> protinho

Obrigado, já é menos 3 bugs para nos preocupamos, 

Testasse as Migration? Se não me engano tive a impressão que teve uma issue dizendo que atualizou o BD pelo botão e não funcionou, apesar de ter dado a mensagem de atualizado com sucesso.

2021-01-14 22:09 UTC, seitbnao commented
PS C:\xampp\htdocs\mapos_27> php index.php tools migrate
Migrations run successfully
PS C:\xampp\htdocs\mapos_27>

2021-01-14 22:49 UTC, willph commented
> 
> 
> PS C:\xampp\htdocs\mapos_27> php index.php tools migrate
> Migrations run successfully
> PS C:\xampp\htdocs\mapos_27>

pronto ja é menos outro. Depois eu testo o botão atualizar BD baixando a versão 26 e clicando atualizar pra vê.

Obrigado, pelas contribuições e paciência kkkkkkk
Sei que pego bastante no pé, vou vê se manero mais

2021-01-14 23:32 UTC, Pr3d4dor requested changes

2021-01-14 23:32 UTC, Pr3d4dor commented on application/controllers/Financeiro.php
> +            'valor' => $this->input->post('valor'),
Qual o motivo de ter trocado a ordem?

2021-01-14 23:32 UTC, Pr3d4dor commented on application/views/financeiro/lancamentos.php
> +      dateFormat: 'dd/mm/yy',<?php echo $configuration['control_baixa'] == 1 ? 'minDate: 0,maxDate: 0' : '' ?>
Não entendi essa parte

2021-01-14 23:32 UTC, Pr3d4dor commented on composer.json
> +		"mpdf/qrcode": "^1.1"
Arruma identação.

2021-01-14 23:32 UTC, Pr3d4dor commented on composer.json
> +		"mpdf/qrcode": "^1.1"
Outra coisa, porque foi adicionado essa lib de qrcode?

2021-01-14 23:56 UTC, seitbnao commented on composer.json
> +		"mpdf/qrcode": "^1.1"
Foi um erro que apareceu na geração do QRCode dos produtos que o wil estava olhando , a inclusão corrige

2021-01-14 23:56 UTC, seitbnao commented on application/views/financeiro/lancamentos.php
> +      dateFormat: 'dd/mm/yy',<?php echo $configuration['control_baixa'] == 1 ? 'minDate: 0,maxDate: 0' : '' ?>
quando o controle estiver ativo, o datapicker só irá ter a data do dia atuall habilitado

2021-01-14 23:56 UTC, seitbnao commented on application/controllers/Financeiro.php
> +            'valor' => $this->input->post('valor'),
Não teve motivo, acho que fui fazer de outra forma e acabei desordenando

2021-01-14 23:57 UTC, seitbnao commented
> > PS C:\xampp\htdocs\mapos_27> php index.php tools migrate
> > Migrations run successfully
> > PS C:\xampp\htdocs\mapos_27>
> 
> pronto ja é menos outro. Depois eu testo o botão atualizar BD baixando a versão 26 e clicando atualizar pra vê.
> 
> Obrigado, pelas contribuições e paciência kkkkkkk
> Sei que pego bastante no pé, vou vê se manero mais

Fica tranquilo, to aprendendo um bocado de coisa ajudando

2021-01-15 00:11 UTC, Pr3d4dor commented on application/views/financeiro/lancamentos.php
> +      dateFormat: 'dd/mm/yy',<?php echo $configuration['control_baixa'] == 1 ? 'minDate: 0,maxDate: 0' : '' ?>
Recomendo deixar a , na linha de cima e o print do echo em linhas separadas, justamente eu não entendi por estar escrito dessa forma.

2021-01-15 00:15 UTC, Pr3d4dor commented on application/views/financeiro/lancamentos.php
> +      dateFormat: 'dd/mm/yy',<?php echo $configuration['control_baixa'] == 1 ? 'minDate: 0,maxDate: 0' : '' ?>
Talvez seja melhor fazer assim:

```
let controlBaixa = "<?php echo $configuration['control_baixa']; >";
let datePickerOptions = {
    dateFormat: 'dd/mm/yy',
}

if (controlBaixa === '1') {
    datePickerOptions.minDate = 0;
    datePickerOptons.maxDate = 0;
}

$(".datepicker").datepicker(datePickerOptions);
```

2021-01-15 00:16 UTC, Pr3d4dor commented on application/views/financeiro/lancamentos.php
> +      dateFormat: 'dd/mm/yy',<?php echo $configuration['control_baixa'] == 1 ? 'minDate: 0,maxDate: 0' : '' ?>
Outra coisa, esse ajuste, só resolve no front a restrição, seria bom colocar uma verificação no backend no controller também.

2021-01-15 00:26 UTC, Pr3d4dor commented
@seitbnao Só uma sugestão se quiser usar uma padronização nos commits: https://www.conventionalcommits.org/pt-br/v1.0.0/
prefiro que os commits sejam em português mesmo, mas usando essa padronização ajuda no review de PR também

2021-01-16 18:42 UTC, merged