fix/refactor
RamonSilva20/mapos pull request #1151
Opened 2021-01-18 01:31 UTC by Pr3d4dor

- Refatoração da funcionalidade de pagamentos.
- Removido tabela de pagamento que não será mais necessária.
- Padronização de código.

2021-01-18 14:30 UTC, seitbnao commented on application/database/migrations/20210108201419_add_usuarios_lancamentos.php
> +        $this->dbforge->drop_column('emitente', 'cep');
não seria usuarios_id?

2021-01-18 15:06 UTC, willph reviewed
Não está aqui, mas como foi mudado a lógica terá que substituir o código `number_format($r->total, 2, ',', '.')` por `number_format($r->total / 100, 2, ',', '.')` na linha 60 do arquivo `cobrancas.php` na view da pasta `conecte`

2021-01-18 16:20 UTC, willph commented
No arquivo `banco.sql` faltou colocar em `cobranca` a coluna `payment_gateway`.

2021-01-18 16:28 UTC, willph requested changes

2021-01-18 16:28 UTC, willph commented on updates/update_4.27.0_to_4.27.1.sql
> +UPDATE permissoes
Faltou colocar aqui o update para adicionar a coluna `payment_gateway` em cobrança.

2021-01-18 17:11 UTC, willph commented
fora isso em visualizarCobrança.php quando é gerado um link de pagamento continua aparecendo `Abrir em nova aba`  tanto para **LINK** quanto para **PDF** ao invés de fica oculto pois o link se encontra em `Url de pagamento` que por sua vez vem em formato texto e não link.


```
Link | Abrir em nova aba     <<<<<< http://localhost/mapos/index.php/cobrancas/visualizar/2
PDF | Abrir em nova aba     <<<<<< http://localhost/mapos/index.php/cobrancas/visualizar/2
```
![image](https://user-images.githubusercontent.com/17226802/104944751-6cc8d680-5996-11eb-8a23-8b875a73f01e.png)

2021-01-18 17:46 UTC, willph commented
O campo `Expiração | 2021-01-21` poderia ter a formatação para a data vim no padrão brasileiro `DD/MM/YY` ou `DD-MM-YY`.

2021-01-18 17:48 UTC, seitbnao commented
> fora isso em visualizarCobrança.php quando é gerado um link de pagamento continua aparecendo `Abrir em nova aba` tanto para **LINK** quanto para **PDF** ao invés de fica oculto pois o link se encontra em `Url de pagamento` que por sua vez vem em formato texto e não link.
> 
> ```
> Link | Abrir em nova aba     <<<<<< http://localhost/mapos/index.php/cobrancas/visualizar/2
> PDF | Abrir em nova aba     <<<<<< http://localhost/mapos/index.php/cobrancas/visualizar/2
> ```
> 
> ![image](https://user-images.githubusercontent.com/17226802/104944751-6cc8d680-5996-11eb-8a23-8b875a73f01e.png)

aba não é ruim nesses casos Will, nem sempre querem sair do sistema pra poder puxar um boleto..

2021-01-18 18:00 UTC, willph commented
> > fora isso em visualizarCobrança.php quando é gerado um link de pagamento continua aparecendo `Abrir em nova aba` tanto para **LINK** quanto para **PDF** ao invés de fica oculto pois o link se encontra em `Url de pagamento` que por sua vez vem em formato texto e não link.
> > ```
> > Link | Abrir em nova aba     <<<<<< http://localhost/mapos/index.php/cobrancas/visualizar/2
> > PDF | Abrir em nova aba     <<<<<< http://localhost/mapos/index.php/cobrancas/visualizar/2
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/17226802/104944751-6cc8d680-5996-11eb-8a23-8b875a73f01e.png)
> 
> aba não é ruim nesses casos Will, nem sempre querem sair do sistema pra poder puxar um boleto..
> seria bom se mostrar o nome do cliente, lembrando que pode ser PJ,
> CPF_CNPJ - Nome

O que estou dizendo é o caminha que está no link, faça um teste, gere um link de pagamento e veja qual o link que tem nos dois campos mencionado.

Acredito que seja por isso que ele deixou genérico, escrito como Documento.

2021-01-18 21:46 UTC, seitbnao commented
Não sei ai mais aqui no menu vendas me apareceu este erro
![Screenshot_14](https://user-images.githubusercontent.com/11374956/104965398-6a2da780-59bd-11eb-9b74-fd0ae00f0bd1.png)

2021-01-18 21:51 UTC, willph commented
> Não sei ai mais aqui no menu vendas me apareceu este erro
> ![Screenshot_14](https://user-images.githubusercontent.com/11374956/104965398-6a2da780-59bd-11eb-9b74-fd0ae00f0bd1.png)

Qual local de vendas?
Aqui está funcionando tranquilamente.

2021-01-18 21:52 UTC, seitbnao requested changes

2021-01-18 21:52 UTC, seitbnao commented on application/controllers/Vendas.php
> +            true,
remover a ,

2021-01-18 21:53 UTC, seitbnao commented
> > Não sei ai mais aqui no menu vendas me apareceu este erro
> > ![Screenshot_14](https://user-images.githubusercontent.com/11374956/104965398-6a2da780-59bd-11eb-9b74-fd0ae00f0bd1.png)
> 
> Qual local de vendas?
> Aqui está funcionando tranquilamente.

linha 164 controller das vendas

2021-01-18 22:06 UTC, willph commented
> > > Não sei ai mais aqui no menu vendas me apareceu este erro
> > > ![Screenshot_14](https://user-images.githubusercontent.com/11374956/104965398-6a2da780-59bd-11eb-9b74-fd0ae00f0bd1.png)
> > 
> > 
> > Qual local de vendas?
> > Aqui está funcionando tranquilamente.
> 
> linha 165 controller das vendas

Aqui está assim. 

![16110075016011584811710268638553](https://user-images.githubusercontent.com/17226802/104966611-1b354180-59c0-11eb-8e25-32364ec9bbea.jpg)

2021-01-18 22:08 UTC, seitbnao commented
sim wil, essa , depois do true na linha 165 bugou aqui, não sei o porque pode ver meu php ou versão de algo

2021-01-18 22:45 UTC, willph commented
~

> 
> 
> sim wil, essa , depois do true na linha 165 bugou aqui, não sei o porque pode ver meu php ou versão de algo

aqui esta normal.

2021-01-18 22:47 UTC, Pr3d4dor commented
@seitbnao é a versão do PHP, só aceita trailing comma em PHP 7.4 pra cima se não me engano o correto é deixar sem mesmo, vou retirar.

2021-01-18 23:34 UTC, seitbnao approved these changes

2021-01-19 21:46 UTC, willph requested changes

2021-01-19 21:46 UTC, willph commented on updates/update_4.27.0_to_4.27.1.sql
> +ALTER TABLE cobranca
`COBRANCAS` ao invés de `cobranca`.

2021-01-20 00:43 UTC, willph approved these changes

2021-01-20 12:40 UTC, willph commented
pode fazer merge. 

Passou no teste de redirecionamento

2021-01-20 23:14 UTC, merged