Melhorias nos relatorios
RamonSilva20/mapos pull request #1358
Opened 2021-04-24 07:55 UTC by hoshikawakun

Fiz algumas melhorias nos relatórios
e Add algo bem interessante no relatório de produtos

![Screenshot_110](https://user-images.githubusercontent.com/1253576/115951739-cde1d800-a4b8-11eb-9055-780191c59741.png)

Add a coluna Valor Estoque que mostra o valor referente a quantidade do referio item
Ex: Jogo PS2 que e vendido a 5,00 e possue 3 itens no estoque, o valor apresentado em Valor Estoque e de 15,00

No Final do Relatório de produtos coloquei para apresentar a quantidade geral de itens que tem no estoque
E outro campo contendo o valor de venda do estoque

2021-04-28 17:05 UTC, hoshikawakun commented
Alguem poderia me ajudar, como faço para resolver esses conflitos?

2021-04-29 23:24 UTC, Pr3d4dor commented
@hoshikawakun Enquanto não resolver os conflitos, não é possível fazer o merge.

Você tem que analisar arquivo por arquivo e resolver os problemas.

2021-04-30 00:58 UTC, hoshikawakun commented
> 
> 
> @hoshikawakun Enquanto não resolver os conflitos, não é possível fazer o merge.
> 
> Você tem que analisar arquivo por arquivo e resolver os problemas.

Creio que consegui resolver os conflitos

2021-04-30 01:12 UTC, Pr3d4dor requested changes

2021-04-30 01:12 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
> +			$writer->writeSheetHeader('Sheet1', $cabecalho);
```suggestion
$writer->writeSheetRow(null, []);
$writer->writeSheetHeader('Sheet1', $cabecalho);
```

2021-04-30 01:12 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
> +				$totalVendas,
Arrumar indentação.

2021-04-30 01:12 UTC, Pr3d4dor commented on application/models/Relatorios_model.php
> +        $this->db->order_by('vendas.idVendas', 'ASC');
Qual o motivo de comentar essas linhas?

2021-04-30 01:12 UTC, Pr3d4dor commented on application/models/Relatorios_model.php
> +       // WHERE idVendas != 0 $whereData $whereCliente $whereResponsavel ORDER BY vendas.dataVenda";
Não deixar código comentado.

2021-04-30 01:12 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
> +				'#' => 'string',
Qual o motivo do item "#" no array?

2021-04-30 01:30 UTC, hoshikawakun commented on CHANGELOG.md
>  ## [4.16.0] - 2020-10-04
Como nunca tinha feito não sabia

2021-04-30 01:32 UTC, hoshikawakun commented on application/models/Relatorios_model.php
> +        $this->db->order_by('vendas.idVendas', 'ASC');
tinha comentado pra eu não esquecer caso não funcionasse e acabei esquecendo de tirar no final

2021-04-30 01:36 UTC, hoshikawakun commented on application/controllers/Relatorios.php
> +				'#' => 'string',
e o idVendas

2021-04-30 01:50 UTC, hoshikawakun commented on CHANGELOG.md
>  ## [4.16.0] - 2020-10-04
Desfiz as mudaças no arquivo

2021-05-06 22:52 UTC, Pr3d4dor requested changes

2021-05-06 22:52 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
> +					'cliente' => $item['nomeCliente'],
```suggestion
		'cliente' => $item['nomeCliente'],
```

2021-05-06 22:52 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
> +				'#' => 'string',
Arrumar indentação.

2021-05-06 22:52 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
>              ]);
Arrumar indentação.

2021-05-06 22:52 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
> +					'cliente' => $item['nomeCliente'],
Indentação.

2021-05-06 22:52 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
> +				$totalVendas,
Indentação.

2021-05-06 22:52 UTC, Pr3d4dor commented on application/models/Relatorios_model.php
> -        $this->db->select('vendas.*,clientes.nomeCliente, usuarios.nome,itens_de_vendas.subTotal as valorTotal, itens_de_vendas.vendas_id');
Por que removido esses campos?

2021-05-06 22:52 UTC, Pr3d4dor commented on application/models/Relatorios_model.php
> -        $this->db->order_by('vendas.dataVenda', 'DESC');
Porque removido?

2021-05-06 22:52 UTC, Pr3d4dor commented on application/models/Relatorios_model.php
> -        $this->db->join('itens_de_vendas', 'itens_de_vendas.vendas_id = vendas.idVendas');
Porque removido?

2021-05-06 22:52 UTC, Pr3d4dor commented on application/models/Relatorios_model.php
> -        $query = "SELECT vendas.*,clientes.nomeCliente, usuarios.nome,itens_de_vendas.subTotal as valorTotal, itens_de_vendas.vendas_id FROM vendas
Porque removido campos

2021-05-07 19:03 UTC, hoshikawakun commented on application/controllers/Relatorios.php
>              ]);
> indentação.

OQUE SERIA indentação.

2021-05-07 19:07 UTC, hoshikawakun commented on application/models/Relatorios_model.php
> -        $this->db->join('itens_de_vendas', 'itens_de_vendas.vendas_id = vendas.idVendas');
> 
> 
> Porque removido?

Do jeito que os relatórios ficaram organizados o de vendas mais especifico, não era mais utilizado essas infos por isso as removi

2021-05-07 19:10 UTC, hoshikawakun commented on application/models/Relatorios_model.php
> -        $this->db->order_by('vendas.dataVenda', 'DESC');
> 
> 
> Porque removido?

Do jeito que os relatórios ficaram organizados o de vendas mais especifico, não era mais utilizado essas infos por isso as removi

Como falei o relatorio de vendas ele estava apresentando as informações da tabela **"itens_de_vendas"** e ao meu ver o relatorio estava confuso, então fiz as alteraçoes para ele apresentar o relatorio da tabela **"vendas"**

2021-05-07 19:11 UTC, hoshikawakun commented on application/models/Relatorios_model.php
> -        $query = "SELECT vendas.*,clientes.nomeCliente, usuarios.nome,itens_de_vendas.subTotal as valorTotal, itens_de_vendas.vendas_id FROM vendas
> 
> 
> Porque removido campos
Do jeito que os relatórios ficaram organizados o de vendas mais especifico, não era mais utilizado essas infos por isso as removi

Como falei o relatorio de vendas ele estava apresentando as informações da tabela **"itens_de_vendas"** e ao meu ver o relatorio estava confuso, então fiz as alteraçoes para ele apresentar o relatorio da tabela **"vendas"**

2021-05-07 19:11 UTC, hoshikawakun commented on application/models/Relatorios_model.php
> -        $this->db->select('vendas.*,clientes.nomeCliente, usuarios.nome,itens_de_vendas.subTotal as valorTotal, itens_de_vendas.vendas_id');
> 
> 
> Por que removido esses campos?

Do jeito que os relatórios ficaram organizados o de vendas mais especifico, não era mais utilizado essas infos por isso as removi

Como falei o relatorio de vendas ele estava apresentando as informações da tabela **"itens_de_vendas"** e ao meu ver o relatorio estava confuso, então fiz as alteraçoes para ele apresentar o relatorio da tabela **"vendas"**

2021-05-07 23:56 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
>              ]);
Indentação se refere ao "espaçamento" do código:

https://pt.wikipedia.org/wiki/Indenta%C3%A7%C3%A3o

2021-05-08 00:58 UTC, hoshikawakun commented on application/controllers/Relatorios.php
>              ]);
> 
> 
> Indentação se refere ao "espaçamento" do código:
> 
> https://pt.wikipedia.org/wiki/Indenta%C3%A7%C3%A3o

estou usando outro programa pra verificar isso pois no que eu utilizo estava tudo certinho
Ja estou fazendo as correções

2021-05-22 10:50 UTC, cabralwms commented
Achei interessante colocar do lado esquerda uma contagem isso seria legal tambem em ordem de serviço, tanto vendas quanto ordens de serviços.

2021-05-22 17:51 UTC, Pr3d4dor approved these changes

2021-05-22 17:52 UTC, Pr3d4dor commented
@hoshikawakun Eu testei essa PR e encontrei alguns problemas, fiz a correção nessa própria PR.

2021-05-22 17:52 UTC, merged

2021-05-22 17:52 UTC, willph commented
Você é o cara @Pr3d4dor.
Obrigado.