Adicionado o controle de edição de OS com status APROVADO
RamonSilva20/mapos pull request #1368
Opened 2021-04-30 16:07 UTC by fwsund

Adicionado o controle de edição de OS com status APROVADO

2021-04-30 16:09 UTC, fwsund commented
acho que agora fiz certo @Pr3d4dor, to apanhando aqui do git pq por algum motivo tem um usuario fwsund e fwsundsa... tenho que arrumar isso

2021-05-06 22:34 UTC, Pr3d4dor commented on application/views/os/os.php
> +                                $cor = '#808080';
Sugestão: Arrumar indentação do código.

2021-05-06 22:34 UTC, Pr3d4dor commented on application/views/os/os.php
> +				<option value="Aprovado">Aprovado</option>
Sugestão: Arrumar indentação do código.

2021-05-06 22:34 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +} ?> value="Aprovado">Aprovado
Sugestão: Arrumar indentação do código.

2021-05-06 22:35 UTC, Pr3d4dor commented on application/views/os/adicionarOs.php
> +												<option value="Aprovado">Aprovado</option>
Sugestão: Arrumar indentação do código.

2021-05-06 22:36 UTC, Pr3d4dor requested changes

2021-05-06 22:36 UTC, Pr3d4dor commented on application/database/migrations/20210125173739_add_os_status_list.php
> +        $sql = "INSERT INTO `configuracoes` (`idConfig`, `config`, `valor`) VALUES (12, 'os_status_list', '[\"Aberto\",\"Faturado\",\"Negocia\\u00e7\\u00e3o\",\"Em Andamento\",\"Or\\u00e7amento\",\"F
Vai ter que fazer um SQL para atualizar bancos já existentes também.

2021-05-06 22:36 UTC, Pr3d4dor commented on CHANGELOG.md
> +
Remover esse trecho de código pos é quando eu lanço versão que preencho.

2021-05-07 17:42 UTC, cabralwms commented
Essa opção de aprovação seria possivel o proprio cliente logar na area cliente e ele mesmo aprovar???

2021-05-07 17:51 UTC, fwsund commented
@cabralwms, a principio nao sera possivel o cliente aprovar, mas sim essa e minha ideia, deixar que o proprio cliente atravez da sua area aprovar o mesmo. O problema que o git pra mim e bem complexo e ainda estou me acostumando a trabalhar nele.

2021-05-22 19:43 UTC, closed without merging