Add % Lucro em Add e Edit Produtos e Add % de Desconto em Faturar Venda e OS
RamonSilva20/mapos pull request #1373
Opened 2021-05-02 17:40 UTC by hoshikawakun

[#1362](https://github.com/RamonSilva20/mapos/issues/1362)

Add Campo **Margem** para calculo do valor de venda com % de lucro em Add e Editar Produtos
![Screenshot_129](https://user-images.githubusercontent.com/1253576/116822093-4bf64c80-ab53-11eb-93e0-571dcb07ce58.png)

Add em Faturar OS o campo **Desconto** que gera o calculo do valor com desconto em X%
![Screenshot_130](https://user-images.githubusercontent.com/1253576/116822195-dccd2800-ab53-11eb-90da-ca1eb648ad34.png)

Após ter o valor com desconto só preencher o campo **Valor** com o novo valor

Add em Faturar Venda o campo **Desconto** que gera o calculo do valor com desconto em X%
![Screenshot_131](https://user-images.githubusercontent.com/1253576/116822258-3df4fb80-ab54-11eb-9aa8-0bc0b0a7f514.png)

Após ter o valor com desconto só preencher o campo **Valor** com o novo valor

2021-05-03 00:50 UTC, hoshikawakun commented
Não editei o arquivo **CHANGELOG.md**

2021-05-06 22:48 UTC, Pr3d4dor requested changes

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +                                            <th width="10%">Sub-total</th>
Sugestão: Arrumar indentação.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +                                            echo '</tr>';
Sugestão: Arrumar indentação.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +                      </div>
Sugestão: Arrumar indentação.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> -                            <option value="Cheque">Cheque</option>
Sugestão: Não remover opção que outros possam estar utilizando.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +    }
Não da pra deixar o texto 'Preço com Desconto' sempre escrito lá no HTML porém com classe hidden para não aparecer e quando calcular o valor retirar a classe para aparecer?

Fica melhor do que fazer concatenação no JS.

Arrumar indentação.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> -            $('#valor').val(valor + total_servico);
Porque esse código foi removido?

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +				$("#idProduto").val(ui.item.id);
Arrumar indentação e porque código de barra está aqui?

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> -                    required: true
Porque foi removido?

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> -                    required: 'Campo Requerido.'
Porque foi removido?

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> -                },
Porque foi removido?

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> -                },
Porque foi removido?

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +                        }
Essa parte de equipamento já funciona?

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +					data: "idServico=" + idServico + "&idOs=" + idOS,
Arrumar indentação

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +				data: "idOs=" + idOS,
Arrumar indentação.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +        });
Equipamento já funcionando?

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +					data: "idAnotacao=" + idAnotacao + "&idOs=" + idOS,
Arrumar indentação.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/os/editarOs.php
> +			var link = $(this).attr('link');
Arrumar indentação.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/produtos/adicionarProduto.php
> +	}
Mes coisa do outro comentário.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/vendas/editarVenda.php
> -                            <option value="Cheque">Cheque</option>
Não remover.

2021-05-06 22:48 UTC, Pr3d4dor commented on application/views/vendas/editarVenda.php
> +	}
Mesma coisa dos comentários anteriores e mesma função sendo duplicada em vários arquivos, talvez seria melhor separar ela.

2021-05-07 19:16 UTC, hoshikawakun commented on application/views/os/editarOs.php
> -                            <option value="Cheque">Cheque</option>
> 
> 
> Sugestão: Não remover opção que outros possam estar utilizando.

essa parte do codigo peguei da minha vers que utilizo por isso não tem a opção de cheque

2021-05-07 19:17 UTC, hoshikawakun commented on application/views/vendas/editarVenda.php
> +	}
> 
> 
> Mesma coisa dos comentários anteriores e mesma função sendo duplicada em vários arquivos, talvez seria melhor separar ela.

Como não sei muito de programação PHP eu apenas peguei as linhas que estavam funcionando e pra add a função em outra pagina eu duplico toda a linha de comando, então oque esta comentado em uma acaba indo para a outra

2021-05-07 19:18 UTC, hoshikawakun commented on application/views/produtos/adicionarProduto.php
> +	}
> 
> 
> Mes coisa do outro comentário.

Como não sei muito de programação PHP eu apenas peguei as linhas que estavam funcionando e pra add a função em outra pagina eu duplico toda a linha de comando, então oque esta comentado em uma acaba indo para a outra

2021-05-07 19:20 UTC, hoshikawakun commented on application/views/vendas/editarVenda.php
> -                            <option value="Cheque">Cheque</option>
> 
> 
> Não remover.

essa parte do codigo peguei da minha vers que utilizo por isso não tem a opção de cheque

2021-05-07 19:21 UTC, hoshikawakun commented on application/views/vendas/editarVenda.php
> -                            <option value="Cheque">Cheque</option>
irei fazer as alterações e add ela novamente

2021-05-07 19:21 UTC, hoshikawakun commented on application/views/os/editarOs.php
> -                            <option value="Cheque">Cheque</option>
irei fazer as alterações e add ela novamente

2021-05-07 19:32 UTC, hoshikawakun commented on application/views/os/editarOs.php
> -            $('#valor').val(valor + total_servico);
> 
> 
> Porque esse código foi removido?

Removi pois devido a algumas melhorias no codigo não era mais preciso desse codigo, se repara agora ao faturar a OS o valor apresentado la sempre tem agora todos os digitos inclusive os depois do **.**
Vou Exemplificar
a OS juntando serviços e produtos totalizando 100,00 no campo valor aparecia apenas 100
agora aparece 100.00 ou seja agora esta aparecendo todas as casas dos centavos, mesmo que seja um valor inteiro sem centavos

2021-05-07 19:33 UTC, hoshikawakun commented on application/views/os/editarOs.php
> -                    required: true
> 
> 
> Porque foi removido?

Apenas para tirar a obrigatoriedade de se preencher o campo la dentro da OS

2021-05-07 19:33 UTC, hoshikawakun commented on application/views/os/editarOs.php
> -                    required: 'Campo Requerido.'
Apenas para tirar a obrigatoriedade de se preencher o campo la dentro da OS

2021-05-07 19:35 UTC, hoshikawakun commented on application/views/os/editarOs.php
> +				$("#idProduto").val(ui.item.id);
> 
> 
> Arrumar indentação e porque código de barra está aqui?
Sobre o Codigo de Barras e prq na minha versão em produtos ali dentro da OS apresenta o Cod de Barras, irei remover esse detalhe que no sistema não tem OK

2021-05-07 19:35 UTC, hoshikawakun commented on application/views/os/editarOs.php
> -                },
Removi pois devido a algumas melhorias no codigo não era mais preciso desse codigo, se repara agora ao faturar a OS o valor apresentado la sempre tem agora todos os digitos inclusive os depois do .
Vou Exemplificar
a OS juntando serviços e produtos totalizando 100,00 no campo valor aparecia apenas 100
agora aparece 100.00 ou seja agora esta aparecendo todas as casas dos centavos, mesmo que seja um valor inteiro sem centavos

2021-05-07 19:36 UTC, hoshikawakun commented on application/views/os/editarOs.php
> -                },
Removi pois devido a algumas melhorias no codigo não era mais preciso desse codigo, se repara agora ao faturar a OS o valor apresentado la sempre tem agora todos os digitos inclusive os depois do .
Vou Exemplificar
a OS juntando serviços e produtos totalizando 100,00 no campo valor aparecia apenas 100
agora aparece 100.00 ou seja agora esta aparecendo todas as casas dos centavos, mesmo que seja um valor inteiro sem centavos

mas vou verificar essas infos que no meu codigo não possue

2021-05-07 19:43 UTC, hoshikawakun commented on application/views/os/editarOs.php
> +        });
Funciona sim perfeitamente mas só não consegui colocar para caso pesquise algo ele faça leitura e apresente a OS referente ao equipamento

vou fazer uma PR somente dessa função Ok

2021-05-07 22:16 UTC, hoshikawakun commented on application/views/os/editarOs.php
> +				$("#idProduto").val(ui.item.id);
> 
> 
> Arrumar indentação e porque código de barra está aqui?

Como essa parte do código refere ao Auto Complete, o Código de barra esta aki para se o usuario tiver um leitor de Codigo de barra ou digitar ele o produto ira aparecer

2021-05-07 22:20 UTC, hoshikawakun commented on application/views/os/editarOs.php
> -                },
> 
> 
> Porque foi removido?

Não Lembro o PRQ de ter removido, Vou Add Novamente

2021-05-11 23:35 UTC, hoshikawakun commented
Se preferir posso finalizar essa PR e abrir novamente com as alterações ja feitas para facilitar

2021-05-22 18:15 UTC, Pr3d4dor approved these changes

2021-05-22 18:16 UTC, merged