Add function discount
RamonSilva20/mapos pull request #1414
Opened 2021-05-29 17:19 UTC by willph

Added the discount function in OS, Sale and Launch

2021-05-30 01:12 UTC, Pr3d4dor requested changes

2021-05-30 01:12 UTC, Pr3d4dor commented on application/controllers/Relatorios.php
> +            force_download('relatorio_os.xlsx', $arquivo);
Sugestão: Acho melhor não renomear o arquivo gerado.

2021-05-30 01:12 UTC, Pr3d4dor commented on application/database/migrations/20210125173741_add_desconto_lancamento.php
> +        $this->db->query("ALTER TABLE `lancamentos` ADD `valor_desconto` VARCHAR(55) NULL;");
Sugestão: Acho que é melhor salvar o valor_desconto como decimal(10, 2) e porque o campo desconto é int?

2021-05-30 01:12 UTC, Pr3d4dor commented on application/database/migrations/20210125173742_add_desconto_os_venda.php
> +        $this->db->query("ALTER TABLE `vendas` ADD `valor_desconto` VARCHAR(55) NULL;");
Sugestão: Acho que é melhor salvar o valor_desconto como decimal(10, 2) e porque o campo desconto é int?

2021-05-30 01:12 UTC, Pr3d4dor commented on application/views/os/imprimirOs.php
> +                            if ($result->valor_desconto != null && $result->desconto != '') {
Sugestão: Ao criar os campos valor_desconto e desconto se deixar o DEFAULT deles como 0, não precisa fazer esse IF e com isso pode ser sempre descontado do valor total.

2021-05-30 01:12 UTC, Pr3d4dor commented on application/views/os/imprimirOsTermica.php
> +                                                            if ($result->valor_desconto != null && $result->desconto != '') {
Sugestão: Ao criar os campos valor_desconto e desconto se deixar o DEFAULT deles como 0, não precisa fazer esse IF e com isso pode ser sempre descontado do valor total.

2021-05-30 01:12 UTC, Pr3d4dor commented on application/views/relatorios/imprimir/imprimirVendas.php
> +                                    <td align="right"></td>
Sugestão: Ao invés de adicionar duas colunas vazias, pode alterar o colspan de cima para 5.

2021-05-30 01:12 UTC, Pr3d4dor commented on application/views/vendas/imprimirVenda.php
> +                                    <?php if ($result->desconto && $result->valor_desconto) { ?>
Sugestão: Ao criar os campos valor_desconto e desconto se deixar o DEFAULT deles como 0, não precisa fazer esse IF e com isso pode ser sempre descontado do valor total.

2021-05-30 01:12 UTC, Pr3d4dor commented on application/views/vendas/imprimirVendaTermica.php
> +                                    <?php if ($result->desconto && $result->valor_desconto) { ?>
Sugestão: Ao criar os campos valor_desconto e desconto se deixar o DEFAULT deles como 0, não precisa fazer esse IF e com isso pode ser sempre descontado do valor total.

2021-05-30 01:12 UTC, Pr3d4dor commented on application/views/vendas/visualizarVenda.php
> +                        <?php if ($result->desconto && $result->valor_desconto) { ?>
Sugestão: Ao criar os campos valor_desconto e desconto se deixar o DEFAULT deles como 0, não precisa fazer esse IF e com isso pode ser sempre descontado do valor total.

2021-05-30 01:12 UTC, Pr3d4dor commented on banco.sql
> +  `valor_desconto` VARCHAR(15) NULL DEFAULT NULL,
Sugestão: colocar desconto e valor_desconto como DECIMAL(10, 2) e com default 0

2021-05-30 02:35 UTC, willph commented on application/controllers/Relatorios.php
> +            force_download('relatorio_os.xlsx', $arquivo);
Pior que não mexe nesse arquivo. 
O máximo que passei nele foi o php-cs-fixer.

2021-05-30 12:25 UTC, willph commented on application/views/vendas/visualizarVenda.php
> +                        <?php if ($result->desconto && $result->valor_desconto) { ?>
Esse if é para aparece ou não o texto na view.

2021-05-30 12:25 UTC, willph commented on banco.sql
> +  `valor_desconto` VARCHAR(15) NULL DEFAULT NULL,
ja corrigido

2021-05-30 12:27 UTC, willph commented on application/views/relatorios/imprimir/imprimirVendas.php
> +                                    <td align="right"></td>
corrigido

2021-06-19 16:43 UTC, infoworkses commented on application/database/migrations/20210125173741_add_desconto_lancamento.php
> +        $this->db->query("ALTER TABLE `lancamentos` ADD `valor_desconto` VARCHAR(55) NULL;");
Observação perfeita.

2021-07-03 03:29 UTC, hoshikawakun commented
To testando sua PR aki e notei alguns problemas
no arquivo  **application/models/Financeiro_model.php** ao editar a linha **42** eu obtenho o seguinte erro
![Screenshot_157](https://user-images.githubusercontent.com/1253576/124341724-cf084300-db94-11eb-91dd-00823d288c32.png)

outro BUG que encontrei foi
Uma OS que seu conteudo de um valor de **300,00** e no campo desconto coloco **50** e mando faturar,
na impressão da OS aparece **Valor Total da OS: R$300,00**, **Desconto: R$ -150,00**  e **Total com Desconto: R$150,00**
ate ai tudo bem
o problema e que o valor a entrar no financeiro não e o valor de **150,00** e sim o valor de **300,00**

2021-07-03 06:23 UTC, willph commented
> To testando sua PR aki e notei um BUG que considero muito grave
> 
> Uma OS que seu conteudo de um valor de **300,00** e no campo desconto coloco **50** e mando faturar,
> na impressão da OS aparece **Valor Total da OS: R$300,00**, **Desconto: R$ -150,00** e **Total com Desconto: R$150,00**
> ate ai tudo bem
> o problema e que o valor a entrar no financeiro não e o valor de **150,00** e sim o valor de **300,00**

Acredito que faltou atualiza banco de dados. Pois tem campo novo para armazenar valor

2021-07-03 09:54 UTC, closed without merging