Alteracoes em os e vendas para desconto em reais
RamonSilva20/mapos pull request #1768
Opened 2022-04-15 03:30 UTC by luizrn

Modificações para alterar em OS, vendas e gateways o método de desconto de porcentagem para valor real.

grande contribuição de @willph

2022-04-15 12:35 UTC, marllonferreira commented
as informaçoes de valor vinda de OS para o lamcamento entao em valores inteiro
exemplo 10
ja os valores de venda estao normal 
exemplo 10.00

recomendo ajusta a tabela lancamentos coluna valor para decimal

2022-04-15 13:10 UTC, marllonferreira commented
apois faturar uma venda ou OS e deixa o pagamento pendente 

![WhatsApp Image 2022-04-15 at 09 58 54](https://user-images.githubusercontent.com/31580600/163573759-3b1dcebc-932e-4411-b76f-28bdca4fd6e6.jpeg)

dai entra em lançamentos para fazer o pagamento a data fica como na imagem acima

2022-04-15 13:17 UTC, marllonferreira commented
![WhatsApp Image 2022-04-15 at 10 10 59](https://user-images.githubusercontent.com/31580600/163574923-cf15c4b1-9f01-4fb0-be89-98d91a56bb98.jpeg)

o que vcs acha de alterar esse nome de **Data Entrada** para **Data Vencimento** ja q la em laçamentos essa mesma data e chmada de Vencimento o que faz sentido quando vc deixa uma OS ou Venda pendente

2022-04-15 13:53 UTC, marllonferreira commented
as coisas acima citada foi tudo que encontrei ficou muito bom parabens pelo otimo trabalho

2022-04-16 07:19 UTC, luizrn commented
> ![WhatsApp Image 2022-04-15 at 10 10 59](https://user-images.githubusercontent.com/31580600/163574923-cf15c4b1-9f01-4fb0-be89-98d91a56bb98.jpeg)
> 
> o que vcs acha de alterar esse nome de **Data Entrada** para **Data Vencimento** ja q la em laçamentos essa mesma data e chmada de Vencimento o que faz sentido quando vc deixa uma OS ou Venda pendente

esse modal nao tem necessidade de mexer agora porque vamos colocar o de parcelamento

2022-04-16 07:24 UTC, luizrn commented
> apois faturar uma venda ou OS e deixa o pagamento pendente
> 
> ![WhatsApp Image 2022-04-15 at 09 58 54](https://user-images.githubusercontent.com/31580600/163573759-3b1dcebc-932e-4411-b76f-28bdca4fd6e6.jpeg)
> 
> dai entra em lançamentos para fazer o pagamento a data fica como na imagem acima

corrigido, verifica a PR #1764 que é so da parte financeira, esse e mais outros que vc mencionou estao corrigidos nelas e estao atualizadas tbm no meu fork com esta PR de troca de desconto de porcentagem por valor real + a do financeiro. Obrigado @marllonferreira, seus testes sao de grande ajuda para agente, vlw mesmo, caso queira testar se os bugs que vc relatou foram corrigidos mesmo, fiquei a vontade para testar (nao alterei ainda os campos do banco de dados de valor para decimal, isso resolve um dos bug que vc encontrou, farei isso mais tarde).

2022-04-16 23:56 UTC, luizrn commented
Trocado os campos do banco.sql de valores para DECIMAL(10, 2) NULL DEFAULT 0, para padronizar e corrigir um bug de calculo de erro na casa de centavos relatado por @marllonferreira .

2022-04-16 23:57 UTC, luizrn commented
> as informaçoes de valor vinda de OS para o lamcamento entao em valores inteiro exemplo 10 ja os valores de venda estao normal exemplo 10.00
> 
> recomendo ajusta a tabela lancamentos coluna valor para decimal
> 
> acredito q seria intereçante muda tudo q for refrente a dinheiro para decimal 10,2

feito. OBG

2022-04-17 13:45 UTC, marllonferreira commented
> > as informaçoes de valor vinda de OS para o lamcamento entao em valores inteiro exemplo 10 ja os valores de venda estao normal exemplo 10.00
> > recomendo ajusta a tabela lancamentos coluna valor para decimal
> > acredito q seria intereçante muda tudo q for refrente a dinheiro para decimal 10,2
> 
> feito. OBG

nao esquece em **migrations** e **updates**

2022-04-17 22:33 UTC, Pr3d4dor commented
@marllonferreira @luizrn Falta mais alguma coisa pra conseguir fazer o merge dessa PR?

2022-04-18 01:19 UTC, luizrn commented
> @marllonferreira @luizrn Falta mais alguma coisa pra conseguir fazer o merge dessa PR?

falta somente migrations e updates so precisa adicionar o tipo DECIMAL(10, 2) NULL DEFAULT 0 no campo valor em lancamentos, OS e vendas, amanha o will disse faz ajuda com isso, nao tenho muito familiaridade com o sistema de update pelo sistema

2022-04-18 22:42 UTC, luizrn commented
> @marllonferreira @luizrn Falta mais alguma coisa pra conseguir fazer o merge dessa PR?

pronto nao tem mais nada, somente precisa ser aprovado junto com a pr do will #1771  e a outra minha do financeiro #1764

2022-04-19 16:22 UTC, luizrn commented
@Pr3d4dor esta tudo certo, só esta com esse problema agora do php fixer depois que mandei um fix do imprimirFinanceiro.php, o @willph tentou mandar a partir do dele como pode ver no histórico mas tbm não resolveu esse problema ai do check do php fixer.

2022-04-19 16:25 UTC, luizrn commented
mas esta ai a correção, quando la de OS ou Vendas nao é marcado como recebido ao faturar, a data vai 0000-00-00, ai se vem desse jeito eu coloquei um "Nao informado" se não aparece a data normal
![image](https://user-images.githubusercontent.com/10822915/164050471-5d5a8303-c266-4bcf-8153-213f0d237277.png)

2022-04-19 18:57 UTC, marllonferreira commented
Refiz os teste funcionou tudo certinho

2022-04-25 00:18 UTC, Pr3d4dor approved these changes

2022-04-29 22:43 UTC, Pr3d4dor commented
@luizrn Consegue arrumar os conflitos?

2022-04-30 00:15 UTC, luizrn commented
> @luizrn Consegue arrumar os conflitos?

Pronto

2022-04-30 00:21 UTC, Pr3d4dor requested changes

2022-04-30 00:21 UTC, Pr3d4dor commented on application/cache/.htaccess
> -deny from all
Manter esse arquivo.

2022-04-30 00:21 UTC, Pr3d4dor commented on application/cache/index.html
> -</html>
Manter esse arquivo.

2022-04-30 00:21 UTC, Pr3d4dor commented on banco.sql
>    `faturado` TINYINT(1) NULL,
Vai dar problema com bancos existentes, teria que criar uma migration para migrar bancos antigos.

2022-04-30 00:21 UTC, Pr3d4dor commented on application/views/vendas/editarVenda.php
> +        let desconto = parseFloat(document.getElementById('desconto').value);
Usar var ao invés de let para compatibilidade com navegadores antigos.

2022-04-30 00:24 UTC, luizrn commented on application/cache/.htaccess
> -deny from all
> Manter esse arquivo.

e se eu apagar o arquivo ou pasta sei la desta PR?, nem sei pq coloquei

2022-04-30 00:26 UTC, Pr3d4dor commented
Não gostei muito dessa implementação, na minha opinião deveria ter a opção dos dois tipos de desconto, tanto por valor e também por porcentagem.

Também não acho que a implementação antiga está correta (%).

2022-04-30 00:40 UTC, luizrn commented
> Não gostei muito dessa implementação, na minha opinião deveria ter a opção dos dois tipos de desconto, tanto por valor e também por porcentagem.
> 
> Também não acho que a implementação antiga está correta (%).

so que agora com as estruturas e banco de dados adequados para o desconto, basta nas bordas (nas telas) em js fazer as opções de porcentagem e valor real, só o importante é mandar para o banco de dados o valor em real, então so fazer isso tudo em js em tempo real conforme o usuário utiliza os campos.

2022-04-30 00:44 UTC, Pr3d4dor commented
@luizrn Deveria ter um campo tipo_desconto, onde 0 = valor e 1 = porcentagem, e com esse tipo, aplicaria o valor do outro campo de acordo. Vai ter que ser refeito a implementação.

2022-04-30 00:50 UTC, luizrn commented
> @luizrn Deveria ter um campo tipo_desconto, onde 0 = valor e 1 = porcentagem, e com esse tipo, aplicaria o valor do outro campo de acordo. Vai ter que ser refeito a implementação.

tbm resolveria o problema, mas de qualquer forma, vai precisar por as 2 opçãoes em JS mesmo, ai ja da de fazer da segunda opção de desconto junto, e nessas 2, ir colocando o valor do desconto final em reais, exemplo: vc da o desconto em %, ai em outro campo vai o valor convertido de % para reais, e assim ao inverso para o outro

COMO NESSE EXEMPLO:
![158491063-6d762e53-27e5-44ac-8ca1-3f3bcc82a643](https://user-images.githubusercontent.com/10822915/166084064-1c64bca0-2681-404c-b4a1-701ecfa20b9e.jpg)

2022-04-30 00:52 UTC, luizrn commented
@Pr3d4dor Ai essa atualização, agente pode fazer depois q sair essa, que é de adicionar mais 1 opção de desconto para %, e tbbm eu e will temos uma ideia, pegar meu modal e funções de parcelamento e trocar pelo do faturar em OS e Vendas

2022-04-30 01:01 UTC, luizrn commented
@Pr3d4dor Removi a pasta chace e mudei a as LET para VAR, ficou somente uma mudança

2022-04-30 01:08 UTC, luizrn commented on application/views/vendas/editarVenda.php
> +        let desconto = parseFloat(document.getElementById('desconto').value);
resolvido

2022-04-30 01:12 UTC, luizrn commented on banco.sql
>    `faturado` TINYINT(1) NULL,
Então mas é aquele problema ne, o usuario q faz o backup errado, instala o sistema novo e vem com o banco antigão por cima, tem que mudar a função de backup já do sistema pra ir somente os dados e não estrutura ja pra futuramente evitar isso

2022-04-30 01:14 UTC, luizrn commented on banco.sql
>    `faturado` TINYINT(1) NULL,
Se o pessoal fizesse backup certo, como somente os dados e não estruturas isso nao seria problema, por isso precisa mudar tbm a função de backup de dentro do mapos, para que seja somente os dados INSERT

2022-04-30 20:07 UTC, Pr3d4dor commented
@luizrn Eu agradeço a PR, mas iremos refazer toda a implementação do desconto para atender os dois casos, valor e percentual.

2022-04-30 20:07 UTC, closed without merging

2022-04-30 20:09 UTC, luizrn commented
> @luizrn Eu agradeço a PR, mas iremos refazer toda a implementação do desconto para atender os dois casos, valor e percentual.

Ok, tudo bem.

2022-04-30 20:21 UTC, Pr3d4dor commented
@luizrn Além disso iria dar conflito com a PR que abri recentemente pra permitir PHP 8.0 #1786. 
Foi separado dois novos branchs 4.x para o mapos com PHP 7.4 e 5.x para o mapos com PHP 8.0.

Vai ser dado suporte ativo somente ao mapos 5.x. O mapos antigo 4.x na versão de PHP antiga ficará somente correção de bugs. Por isso será recomendado todos atualizarem.

2022-04-30 20:22 UTC, luizrn commented
> @luizrn Além disso iria dar conflito com a PR que abri recentemente pra permitir PHP 8.0 #1786. Foi separado dois novos branchs 4.x para o mapos com PHP 7.4 e 5.x para o mapos com PHP 8.0.
> 
> Vai ser dado suporte ativo somente ao mapos 5.x. O mapos antigo 4.x na versão de PHP antiga ficará somente correção de bugs. Por isso será recomendado todos atualizarem.

Assim entendi

2022-04-30 20:31 UTC, luizrn commented
> @luizrn Além disso iria dar conflito com a PR que abri recentemente pra permitir PHP 8.0 #1786. Foi separado dois novos branchs 4.x para o mapos com PHP 7.4 e 5.x para o mapos com PHP 8.0.
> 
> Vai ser dado suporte ativo somente ao mapos 5.x. O mapos antigo 4.x na versão de PHP antiga ficará somente correção de bugs. Por isso será recomendado todos atualizarem.

Tudo certo, essa pr mesmo foi praticamente do will, só ajudei um pouco, ia falar com ele mas ja deve ta sabendo ne?