Update topo.php
RamonSilva20/mapos pull request #2100
Opened 2023-04-14 00:25 UTC by WillianCamargo01

Retirada dos botões de fullscreen e transferência para o botão F11. Correção do bug que saia do modo tela cheia automaticamente ao clicar em qualquer outro botão do sistema. Definição dos nomes para "Perfis" "Relatórios" e "Configurações" no top da página.

2023-04-16 02:15 UTC, seitbnao requested changes
Manter o nome do sistema.

2023-04-16 02:15 UTC, seitbnao commented on application/views/tema/topo.php
> +  <title><?= $configuration['app_name'] ?: 'Lions' ?></title>
Map-Os

2023-05-02 00:07 UTC, willph commented
O porque da remoção dos **title**?

2023-05-02 01:34 UTC, willph commented
`<i class='bx bx-pie-chart-alt-2 iconN'>` faltou esse

2023-05-02 19:00 UTC, willph commented
Após analise não precisa da função em javascript, apenas precisa comentar a função de captura do F11.

2023-05-02 19:05 UTC, merged