Correção gerencianet para Efipay
RamonSilva20/mapos pull request #2306
Opened 2023-12-16 19:44 UTC by cabralwms

Fiz a correção do api do gerencianet para Efipay, atualizando o composer e arquivos necessários para o funcionamento, corrigindo bug de data ao criar boletos para datas futuras que estava dando erro.

![image](https://github.com/RamonSilva20/mapos/assets/61280919/7de292c0-78ad-41c3-866c-aff39a5d57af)

2023-12-26 14:15 UTC, Fesantt commented
precisa desse rolê todo n mano, só dei updade na biblioteca aqui no meu e ta funcionando de boa

2024-01-18 17:07 UTC, Pr3d4dor commented
@cabralwms Favor atualizar a PR com a sugestão do @Fesantt, precisa apenas atualizar a biblioteca.

2024-01-18 18:13 UTC, cabralwms commented
Fiz a remoção do Gerencianet pelo EFIPAY e assim testado funcionou corretamente.

2024-02-13 03:54 UTC, willph requested changes
No geral é apenas renomear variáveis, textos e correção da dependência no arquivo composer.json/composer.lock 

Pois agora se chama EfiPay o SDK da GerenciaNet.


Obrigado pela PR e fico no aguardo das alterações para aprovar a mesma.

Atenciosamente, Equipe MapOS

2024-02-13 03:54 UTC, willph commented on composer.json
> +        "efipay/sdk-php-apis-efi": "^1.7.1"
Vai precisar remover        ` "efipay/sdk-php-apis-efi": "^1.7.1"` e depois rodar o comando `composer require efipay/sdk-php-apis-efi:^1.7.1 --with-all-dependencies`

Pois a maioria tem o SDK do Gerencianet instalado, com o  comando ele removi e instala o Efipay. 

Do jeito que esta aqui da erro ao rodar o comando `composer install --no-dev`, devido a dependência do Gerencianet ainda esta no composer.lock

2024-02-13 03:54 UTC, willph commented on application/config/payment_gateways.php
Linha 6, 7, 8 precisara altera para o seguinte código 

        `'EfiPaySdk' => [
        'name' => 'EfiPay by GerenciaNet',
        'library_name' => 'EfiPaySdk',`
        
Na linha 32 alterar o nome **Gerencianet** para **EfiPay**

`'refunded' => 'Pagamento devolvido pelo lojista ou pelo intermediador EfiPay',`

2024-02-13 03:54 UTC, willph commented on application/libraries/Gateways/GerencianetSdk.php
Nesse Arquivo precisara renomear o arquivo, para **EfiPaySdk.php** 

Na linha 7 renomear a a class para **EfiPaySdk**

`class EfiPaySdk extends BasePaymentGateway`

Linhas 9, 10 e 12 alterar para

```
/** @var EfiPay $efiPayApi */
    private $efiPayApi;
    private $efiPayConfig;

```

Da linha 24 a 30 alterar

```
        $efiPayConfig = $this->ci->config->item('payment_gateways')['EfiPaySdk'];
        $this->efiPayConfig = $efiPayConfig;
        $this->efiPayApi = new EfiPay([
            'client_id' => $efiPayConfig['credentials']['client_id'],
            'client_secret' => $efiPayConfig['credentials']['client_secret'],
            'sandbox' => $efiPayConfig['production'] !== true,
            'timeout' => $efiPayConfig['timeout'],
```

linha 41 alterar para

`        $response = $this->efiPayApi->cancelCharge(['id' => $cobranca->charge_id], []);
`

linha 43 para

         `   throw new \Exception('Erro ao chamar EfiPay!');`

Linha 103 e 105 para

````
  $result = $this->efiPayApi->detailCharge(['id' => $cobranca->charge_id], []);
      
   throw new \Exception('Erro ao chamar EfiPay!');

````

Linha 138 e 140 para

````
           $response = $this->efiPayApi->settleCharge(['id' => $cobranca->charge_id], []);
            throw new \Exception('Erro ao chamar EfiPay!');
````

Linha 250 para

        `$expirationDate = (new DateTime())->add(new DateInterval($this->efiPayConfig['boleto_expiration']));`

Linha 272 e 274 para

````
        $result = $this->efiPayApi->createOneStepCharge([], $body);
            throw new \Exception('Erro ao chamar EfiPay!');
````

Linha 288 para

`'payment_gateway' => 'EfiPaySdk',`

Linha 368 para

`$response = $this->efiPayApi->createCharge(`

Linha 381 para

           ` throw new \Exception('Erro ao chamar EfiPay!');`
           
Linha 388 para 

`$result = $this->efiPayApi->linkCharge(`


Linha 400 para 

`throw new \Exception('Erro ao chamar EfiPay!');`


Linha 410 para

`'payment_gateway' => 'EfiPaySdk',`

2024-02-14 22:25 UTC, closed without merging