Ajustes do Github_updater.php e captcha
RamonSilva20/mapos pull request #2339
Opened 2024-02-21 01:07 UTC by juliolobo

Removendo a criação de diretório do Github_updater
Refeito geração de captcha
Realocando arquivos de fonte

2024-02-21 01:12 UTC, juliolobo commented
Fiz alguns ajustes no cadastrar.php organizando o arquivo

2024-02-21 01:17 UTC, willph requested changes

2024-02-21 01:17 UTC, willph commented on application/views/conecte/cadastrar.php
>  </html>
linha git

2024-02-21 01:28 UTC, willph approved these changes

2024-02-22 01:08 UTC, Pr3d4dor commented
@juliolobo Eu não entendi muito bem as alterações. Poderia explicar?

2024-02-22 01:39 UTC, juliolobo commented
1 - Eu havia colocado no Github_updater, em outro PR, pra se houvesse diretório novo no github criar no servidor do usuário. Will, Santt e eu testamos local e em produção e funcionou, mas outros usuários reportaram erro quando o script tenta criar o diretório.
Por isso removi nessa att.

2 - Na geração do CAPTCHA para cadastro no Mine, usava um desses diretórios novos, mas sem o script de criação de diretório, refiz a geração de CAPTCHA para não gerar mais uma imagem, dispensando assim o uso do diretório pra salvar as mesmas e também realoquei as fontes usadas no CAPTCHA para um diretório já existente.

3 - Aproveitei que estava mexendo no arquivo cadastrar.php e organizei posição de Scripts JS, dei uma limpada no código.

2024-02-22 20:17 UTC, merged