Fix: Vinculos de Vendas e Os com Lancamentos
RamonSilva20/mapos pull request #2471
Opened 2024-07-07 20:07 UTC by lukasabino

Tais alterações abrangem a forma que a tabela lançamentos se comporta referente as Vendas e Os.

As alterações realizadas foram: 

- Criação de coluna `os_id` na tabela de lancamentos
- Ao faturar uma Os, enviar o os_id para o vinculo na tabela lancamentos
- Alteração na forma de exclusão dos lancamentos ao excluir uma Venda ou Os.

2024-07-11 19:37 UTC, cabralwms commented
Testei e funcionou criando o IDvendas e IDOS amarrando ao lançamento.

2024-07-12 00:40 UTC, willph requested changes

2024-07-12 00:41 UTC, lukasabino commented on updates/update_4.45.0_to_4.46.0.sql
> +ALTER TABLE `vendas` ADD `status` VARCHAR(45) NULL DEFAULT NULL;
Essa alteração foi feita pelo @cabralwms, por algum motivo, no meu commit, foi como se eu tivesse inserido ela.

Não entendi bem o motivo...

2024-07-12 00:46 UTC, lukasabino commented on updates/update_4.45.0_to_4.46.0.sql
> +ALTER TABLE `lancamentos` ADD `os_id` INT(11) NULL DEFAULT NULL;
Adicionado via commit.

2024-07-12 19:58 UTC, willph approved these changes

2024-07-13 14:48 UTC, Pr3d4dor commented
Estou receoso para fazer o merge dessa PR.

Pois a ideia a atual não é fazer mais implementações novas, mas sim correções de bugs. Ainda mais por mexer na estrutura do banco de dados.

2024-07-13 14:52 UTC, lukasabino commented
> Estou receoso para fazer o merge dessa PR.
> 
> Pois a ideia a atual não é fazer mais implementações novas, mas sim correções de bugs. Ainda mais por mexer na estrutura do banco de dados.

Para que seja possível fazer novas implementações, preciso dessa correção. 

A ideia de corrigir este ponto é poder atuar ainda mais em melhorias para a parte financeira do Map-Os que carece de atenção, como faturar Venda/Os ao emitir cobrança, ter essa cobrança também no lançamentos, fazer a baixa automática desses lançamentos e afins.

A falta dessa correção ia impossibilitar qualquer melhora na parte citada, pois manter o "vínculo" dos movimentos somente na descrição do lançamento, não é nem um pouco seguro/confiável.

2024-07-13 14:54 UTC, Pr3d4dor commented
Essa é a questão, a ideia é não ter mais funcionalidades novas, apenas correções de bugs. Senão fica inviável a migração para o Laravel ao mesmo momento que tiver aparecendo coisas novas no mapos antigo.

2024-07-13 15:02 UTC, lukasabino commented
> Essa é a questão, a ideia é não ter mais funcionalidades novas, apenas correções de bugs. Senão fica inviável a migração para o Laravel ao mesmo momento que tiver aparecendo coisas novas no mapos antigo.

Neste caso vejo uma completa incoerência nos últimos acontecimentos no repositório, visto últimos PRs e Commits, se a ideia seria somente a correção de bugs e foco no laravel, tal visão não é clara nem para os usuários, nem para aqueles que se propõe a ajudar.

Mesmo que a ideia não seja implementar tais ações, por mais básicas e pedidas que seja, vejo que tal PR deveria ser mergeada por se tratar de fato uma correção não de BUG, mas por falha na estrutura do sistema. 

Assim como outras PRs de vínculos status e garantias, melhorias em vendas, painel do clientes e afins.

2024-07-13 15:07 UTC, willph commented
> > Essa é a questão, a ideia é não ter mais funcionalidades novas, apenas correções de bugs. Senão fica inviável a migração para o Laravel ao mesmo momento que tiver aparecendo coisas novas no mapos antigo.
> 
> Neste caso vejo uma completa incoerência nos últimos acontecimentos no repositório, visto últimos PRs e Commits, se a ideia seria somente a correção de bugs e foco no laravel, tal visão não é clara nem para os usuários, nem para aqueles que se propõe a ajudar.
> 
> Mesmo que a ideia não seja implementar tais ações, por mais básicas e pedidas que seja, vejo que tal PR deveria ser mergeada por se tratar de fato uma correção não de BUG, mas por falha na estrutura do sistema.
> 
> Assim como outras PRs de vínculos status e garantias, melhorias em vendas, painel do clientes e afins.

Por mim faz o merge.

2024-07-13 15:17 UTC, Pr3d4dor commented
@lukasabino Não é incoerente pois a maioria das mudanças que foram coisas novas foram apenas mudanças de botões de impressão, instalador e coisas de telas e não coisas mais estruturais, é isso que eu me refiro.

2024-07-15 23:47 UTC, lukasabino commented
PR fechada pós decisão em call com Ramon.

2024-07-15 23:47 UTC, closed without merging