#DESAFIO PR Atualização painel com informações
RamonSilva20/mapos pull request #2490
Opened 2024-07-17 18:09 UTC by cabralwms

Após conversar e ver a necessidade de melhores informações no painel, fiz essa melhoria para visualizar assim que entrar no sistema. Tendo as seguintes informações.

Ordens de Serviços em Orçamento (adicionado)
Ordens de Serviços Abertas (já tinha)
Ordens de Serviços Aprovadas (adicionado)
Ordens de Serviços Finalizadas (Adicionado)
Ordens de Serviços Em Andamento e Aguardando Peças ( adicionado)
Ultimos Lançamentos Pendentes (adicionado)
Produtos em Estoque Minimo (movido para ultimo campo)

![image](https://github.com/user-attachments/assets/05aa5de6-b9b6-45ab-9cc6-1cece1e8f77b)

![image](https://github.com/user-attachments/assets/1965384a-308a-43d9-9038-040c11825ec1)

Feita Também a Padronização de ordens de dados (ID, nome cliente, Data inicial, data final, Status, ações.

Para facilitar a visualização colocado o status com cores iguais das ordens de serviços.

2024-07-18 17:00 UTC, willph requested changes

2024-07-18 17:00 UTC, willph commented on application/models/Mapos_model.php
> +        $this->db->limit(5);
O limite aqui sera 5 mesmo?

É apenas uma duvida, visto que nas outras estão 10

2024-07-18 17:28 UTC, cabralwms commented on application/models/Mapos_model.php
> +        $this->db->limit(5);
vou verificar agora , será 10 como combinamos no grupo.

2024-07-19 17:53 UTC, willph approved these changes

2024-07-20 17:17 UTC, merged