Botão Imprimir Recibo nos Lançamentos
RamonSilva20/mapos pull request #2494
Opened 2024-07-18 03:40 UTC by viniciusvams

Adicionada a funcionalidade de imprimir recibo na seção de Lançamentos. Agora, ao listar as receitas, foi incluído um botão para imprimir o recibo.

Ao clicar neste botão, será gerado um recibo que pode ser impresso ou compartilhado com o cliente.

2024-07-20 03:01 UTC, juliolobo requested changes
Essa identação não ficou legal.
Não sei se usou alguma ferramenta pra identar, mas não ficou bacana não.

2024-07-20 03:13 UTC, viniciusvams commented
Mais seria em todos os arquivos ou em algum especifico? :)

> Essa identação não ficou legal. Não sei se usou alguma ferramenta pra identar, mas não ficou bacana não.

2024-07-20 03:33 UTC, viniciusvams commented
atualizei a indentação, vê se ficou bom  :)

2024-07-20 12:36 UTC, viniciusvams commented
Entendi, pode deixar, vou reinstalar a ide e ajustar esses problemas. :)

> O problema é tudo ![image](https://private-user-images.githubusercontent.com/13459803/350689958-0827b92c-c679-4e5b-b746-4775d16bec21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzkyMDYsIm5iZiI6MTcyMTQ3ODkwNiwicGF0aCI6Ii8xMzQ1OTgwMy8zNTA2ODk5NTgtMDgyN2I5MmMtYzY3OS00ZTViLWI3NDYtNDc3NWQxNmJlYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEyMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NGQ4NTBiMzc2MTc4YTQ3N2M2ZDIxZjdjNzhjODk0MDFiYTE4MzQzMTA5NTQxZmQxZDk3NGU1MjRiMjE1NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8kbaO21y_cbBNs4PKEaNmL6fw164tIF6ttc6_ihIEsM) ![image](https://private-user-images.githubusercontent.com/13459803/350690117-0bac28c2-e52b-462b-80cb-05ba5febe62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzkyMDYsIm5iZiI6MTcyMTQ3ODkwNiwicGF0aCI6Ii8xMzQ1OTgwMy8zNTA2OTAxMTctMGJhYzI4YzItZTUyYi00NjJiLTgwY2ItMDViYTVmZWJlNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEyMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYWUzZDc3MzRjMDRlMmQ1ZTc1MDUxYmIxNDIxNjg4ZjdlYmYxY2I5MDBiNDI1ODBmYTkxMzU0NmY2MzFiYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Hr-8WKF4adIvn_aXjevU1b2ig9mdY5eGmZi73_oX8w)
> 
> Foram mudanças desnecessárias e que pioram a legibilidade do código. E isso aconteceu em todos os arquivos que vc mexeu. Provavelmente foi alguma ferramenta que vc usou ou alguma extensão do VSCode.

2024-07-21 03:50 UTC, viniciusvams commented
Ola, agora acredito que esteja certo a questão da indentação. valeu :)


> O problema é tudo ![image](https://private-user-images.githubusercontent.com/13459803/350689958-0827b92c-c679-4e5b-b746-4775d16bec21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzQwODksIm5iZiI6MTcyMTUzMzc4OSwicGF0aCI6Ii8xMzQ1OTgwMy8zNTA2ODk5NTgtMDgyN2I5MmMtYzY3OS00ZTViLWI3NDYtNDc3NWQxNmJlYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDAzNDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOTY1Mjk5ZWI0ZTU0OWQ2ZjFjZjA0ODQ0YmUzMDA5OGJhNzRkZGE3YmMwZTAwYzk3NjhkODQ2MDYzNzhlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vBuZk57WOCgdlO3KBK9_bgmOg_VPGAUAHY204wD-se0) ![image](https://private-user-images.githubusercontent.com/13459803/350690117-0bac28c2-e52b-462b-80cb-05ba5febe62c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzQwODksIm5iZiI6MTcyMTUzMzc4OSwicGF0aCI6Ii8xMzQ1OTgwMy8zNTA2OTAxMTctMGJhYzI4YzItZTUyYi00NjJiLTgwY2ItMDViYTVmZWJlNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDAzNDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYmU0MDliMWEzOTQ5YTEwNTQ5MzYyYWZmMjlkZTU2YWFhMDZkZmUzYWM1NDhlZGZkYzQ4MDJhZmQzNmQ1ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A_v9MgreXCxGykbWM-a5tjQKTnc8fARN7EFXWqzzljE)
> 
> Foram mudanças desnecessárias e que pioram a legibilidade do código. E isso aconteceu em todos os arquivos que vc mexeu. Provavelmente foi alguma ferramenta que vc usou ou alguma extensão do VSCode.

2024-07-21 09:03 UTC, juliolobo commented
@viniciusvams agora sim!!
Só um detalhe.
Nos arquivos, precisa ficar uma linha sobrando.
a gente chama de Linha Git
![image](https://github.com/user-attachments/assets/41e46577-dfc5-4d65-9922-895ab39b1e97)
Confere os arquivos que vc fez alterações e adiciona essa linha no final
Só dá um enter (uma linha vazia).

2024-07-21 18:40 UTC, viniciusvams commented
:) Acabei de add essa linha a mais no filna :)

> @viniciusvams agora sim!! Só um detalhe. Nos arquivos, precisa ficar uma linha sobrando. a gente chama de Linha Git ![image](https://private-user-images.githubusercontent.com/13459803/350748975-41e46577-dfc5-4d65-9922-895ab39b1e97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1ODc1MTEsIm5iZiI6MTcyMTU4NzIxMSwicGF0aCI6Ii8xMzQ1OTgwMy8zNTA3NDg5NzUtNDFlNDY1NzctZGZjNS00ZDY1LTk5MjItODk1YWIzOWIxZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE4NDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTI0NDYyNGIwMmNmNTZhNjNmMzY0ODY1ZTA1ZTBhZjBmZTNkYjI5Y2UwYzA4MzcxZGIzODFjMDYxZWE3YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zKLowJVt56FlRz0rv43SsAAn6xatDUPkuZTfzU-Dlfk) Confere os arquivos que vc fez alterações e adiciona essa linha no final Só dá um enter (uma linha vazia).

2024-07-22 22:48 UTC, Pr3d4dor commented
@viniciusvams eu vou precisar testar e ver sua PR localmente, quero ajustar algumas coisas e vou fazer algumas modificações direto no mesmo branch. Peço um pouco de paciência.

2024-07-22 23:05 UTC, viniciusvams commented
Tranquilo amigo, eu tô usando em produção essa funcionalidade, até agora não apresentou nenhum bug.

Mais fico no aguardo, muito obrigado:)

Espero poder participar de futuras atualizações, vi que estão preparando uma nova versão.

> @viniciusvams eu vou precisar testar e ver sua PR localmente, quero ajustar algumas coisas e vou fazer algumas modificações direto no mesmo branch. Peço um pouco de paciência.

2024-08-17 03:27 UTC, viniciusvams commented
@Pr3d4dor conseguiu testar amigo? :)

2024-08-17 13:08 UTC, willph commented
Infelizmente esta versão não receberá mais atualizações.

Muito obrigado pela atenção dada ao projeto.

Qualquer nova PR será aceita na versão do MapOs em Laravel.


A equipe agradece de coração o empenho.

Atenciosamente Equipe MapOs.

2024-08-17 13:08 UTC, closed without merging

2024-08-17 20:00 UTC, Andersondemoura commented
Boa tarde vinicius, cara eu fiz todo procedimento que você fez porém quando vou imprimir o recibo o mesmo fica em branco, consegue me ajudar? segue img
![Sem título](https://github.com/user-attachments/assets/6b1b8846-2f37-4af3-9f11-e9cb3da0320b)