Melhorias gerais
RamonSilva20/mapos pull request #2510
Opened 2024-07-27 13:04 UTC by WillianCamargo01

Melhoraia na visualização das tabelas, correções de bugs na tela de lançamento para o filtro personalizado e melhorias na visualização da data de expiração do usuario

2024-07-27 15:16 UTC, willph commented
Obrigado pela contribuição. Teria um print das alterações feita?

Ótimo dia
Bom final de semana

2024-07-31 11:49 UTC, WillianCamargo01 commented
![image](https://github.com/user-attachments/assets/e0cb89f0-43da-4308-8d9f-4801fb12c0a5)
![image](https://github.com/user-attachments/assets/b94795fd-4d4b-4019-8fad-17acec484359)
![image](https://github.com/user-attachments/assets/69984f1e-24a8-422a-8e7f-f8ac0b200b62)
![image](https://github.com/user-attachments/assets/d001c3e8-02a3-4fed-9895-a471876a5dcc)
![image](https://github.com/user-attachments/assets/a18e26d8-d6b3-48df-89bb-30e846a6b33a)

2024-08-03 21:13 UTC, willph requested changes

2024-08-03 21:13 UTC, willph commented on application/views/produtos/editarProduto.php
> +</script>
Após a linha 252 precisa de uma linha em branco.

2024-08-03 21:13 UTC, willph commented on application/views/produtos/adicionarProduto.php
> +</script>
Após a linha 236 precisa de uma linha em branco.

2024-08-03 21:13 UTC, willph commented on application/views/usuarios/usuarios.php
> +<?= $this->pagination->create_links(); ?>
Após a linha 82 precisa de uma linha em branco.

2024-08-17 13:07 UTC, willph commented
Infelizmente esta versão não receberá mais atualizações.

Muito obrigado pela atenção dada ao projeto.

Qualquer nova PR será aceita na versão do MapOs em Laravel.


A equipe agradece de coração o empenho.

Atenciosamente Equipe MapOs.

2024-08-17 13:07 UTC, closed without merging