Corrigindo faturar com valores em Vendas
RamonSilva20/mapos pull request #2515
Opened 2024-07-29 21:46 UTC by cabralwms

Corrigindo o Faturar em vendas com valores no banco de dados.

![image](https://github.com/user-attachments/assets/1bd12a59-cb26-4bdb-b2aa-64c8ccd7ffd8)

2024-07-31 11:55 UTC, willph requested changes

2024-07-31 11:55 UTC, willph commented on application/controllers/Vendas.php
> +                    log_info('Faturou uma venda.');
Poderia trazer o nome de quem foi o responsável pelo faturamento da venda?

2024-07-31 12:00 UTC, willph commented on application/controllers/Vendas.php
> +                    log_info('Faturou uma venda.');
Exemplo:

**Fulano** faturou a venda de ID XXX.

2024-07-31 13:51 UTC, cabralwms commented
Pronto Will Feito a correção conforme sugeriu. agora salva o log mostrando quem fez a alteração e ao faturar venda o ID da venda faturada. 

![image](https://github.com/user-attachments/assets/d38dea74-c325-426d-9495-20eecd4b45f6)

2024-08-01 10:29 UTC, cabralwms commented
Feitas correções para ao criar vendas, adicionar produtos, excluir produtos, alterar, dar desconto tudo será gerado logs no audite, com id da venda. Ao Faturar a venda para lançamentos, o ID lançamento tambem é vinculado a venda, se excluir esse lançamento, a venda será atualiada os campos, idlancamentos, status, faturado. Retornando para finalizado o status. 

![image](https://github.com/user-attachments/assets/4dbe51ee-6377-4824-9ebe-3add6659a1e0)

imagens dos teste em auditoria.

2024-08-03 21:01 UTC, willph approved these changes

2024-08-03 21:06 UTC, merged